---
name: "1709"

releases:
- name: windows-tools
  sha1: 7b962d804ad2c09f3c49c964c93d878cc2bba1b0
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/windows-tools-release?v=26
  version: 26
- name: windows-utilities
  sha1: efc10ac0f4acae23637ce2c6f864d20df2e3a781
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/windows-utilities-release?v=0.11.0
  version: 0.11.0

stemcells:
- alias: windows1709
  os: windows2016
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000
  max_in_flight: 3
  max_errors: 2
  serial: false

instance_groups:
- name: 1709-vm
  stemcell: windows1709
  vm_type: winc-vm
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: diego-ssh
    properties:
      diego_ssh:
        public_key: ((DEV_BOX_PUBLIC_KEY))
        port: 2222
    release: windows-tools
  - name: smb-share
    release: windows-tools
  - name: docker
    release: windows-tools
  - name: git
    release: windows-tools
  - name: golang-windows
    release: windows-tools
  - name: load-powershell-env
    release: windows-tools
  - name: mingw64
    release: windows-tools
  - name: ginkgo
    release: windows-tools
  - name: processhacker
    release: windows-tools
  - name: enable_rdp
    properties:
      enable_rdp:
        enabled: true
    release: windows-utilities
  - name: set_password
    properties:
      set_password:
        username: "Administrator"
        password: ((DEV_BOX_PASSWORD))
    release: windows-utilities
  - name: winc-setup
    properties:
      winc_setup:
         docker_tag: "1709"
    release: windows-tools
  instances: 1
  lifecycle: service
