---
name: "2012R2"

releases:
- name: windows-tools
  sha1: 7623d7ef1518fbb396747c2d9e60e337eb80d2c2
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/windows-tools-release?v=24
  version: 24
- name: windows-utilities
  sha1: efc10ac0f4acae23637ce2c6f864d20df2e3a781
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/windows-utilities-release?v=0.11.0
  version: 0.11.0

stemcells:
- alias: windows2012R2
  os: windows2012R2
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000
  max_in_flight: 3
  max_errors: 2
  serial: false

instance_groups:
- name: 2012R2-vm
  stemcell: windows2012R2
  vm_type: winc-vm
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: vs2017
    release: windows-tools
  - name: git
    release: windows-tools
  - name: golang-windows
    release: windows-tools
  - name: load-powershell-env
    release: windows-tools
  - name: mingw64
    release: windows-tools
  - name: processhacker
    release: windows-tools
  - name: enable_rdp
    properties:
      enable_rdp:
        enabled: true
    release: windows-utilities
  - name: smb-share
    release: windows-tools
  - name: set_password
    properties:
      set_password:
        username: "Administrator"
        password: ((DEV_BOX_PASSWORD))
    release: windows-utilities
  instances: 1
  lifecycle: service
