azs:
- name: z1
- name: z2
- name: z3
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: default
  workers: 2
disk_types:
- disk_size: 10000
  name: default
- disk_size: 50000
  name: large
networks:
- name: default
  subnets:
  - azs:
    - z1
    - z2
    - z3
    cloud_properties:
      name: /dev/vmnet8
    dns:
    - 8.8.8.8
    gateway: 192.168.158.2
    range: 192.168.158.0/24
    reserved:
    - 192.168.158.1 - 192.168.158.10
  type: manual
vm_types:
- cloud_properties:
    cpu: 2
    disk: 10240
    ram: 1024
  name: default
- cloud_properties:
    cpu: 2
    disk: 30240
    ram: 4096
  name: large
- cloud_properties:
    cpu: 8
    disk: 131072
    ram: 24576
  name: envoy-builder
