azs:
- name: z1
- name: z2
- name: z3

compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: default
  workers: 2

disk_types:
- disk_size: 10000
  name: default
- disk_size: 50000
  name: large

networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    azs: [z1, z2, z3]
    dns: [8.8.8.8]
    reserved: [((internal_reserved_range))]
    cloud_properties:
      name: ((network_name))

vm_types:
- cloud_properties:
    cpu: 2
    disk: 10240
    ram: 1024
  name: default
- cloud_properties:
    cpu: 2
    disk: 30240
    ram: 4096
  name: large
- cloud_properties:
    cpu: 8
    ram: 24576
  name: envoy-builder
- cloud_properties:
    cpu: 4
    disk: 131072
    ram: 8192
  name: winc-vm
