---
name: envoy

releases:
- name: windows-tools
  version: "43"
  url: "https://bosh.io/d/github.com/cloudfoundry-incubator/windows-tools-release?v=43"
  sha1: "82606431803a37645cca89d24ed7d73b7568ca62"
- name: windows-utilities
  sha1: efc10ac0f4acae23637ce2c6f864d20df2e3a781
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/windows-utilities-release?v=0.11.0
  version: 0.11.0

stemcells:
- alias: windows
  os: windows1803
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000
  max_in_flight: 3
  max_errors: 2
  serial: false

instance_groups:
- name: envoy
  stemcell: windows
  persistent_disk: 204800
  vm_type: envoy-builder
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: bazel
    release: windows-tools
  - name: cmake
    release: windows-tools
  - name: diego-ssh
    properties:
      diego_ssh:
        public_key: ((DEV_BOX_PUBLIC_KEY))
        port: 2222
    release: windows-tools
  - name: git
    release: windows-tools
  - name: load-powershell-env
    release: windows-tools
  - name: make
    release: windows-tools
  - name: msys2
    release: windows-tools
  - name: ninja
    release: windows-tools
  - name: python
    release: windows-tools
  - name: smb-share-envoy
    release: windows-tools
  - name: vc_redist
    release: windows-tools
  - name: vs_buildtools
    release: windows-tools
  - name: enable_rdp
    properties:
      enable_rdp:
        enabled: true
    release: windows-utilities
  - name: set_password
    properties:
      set_password:
        username: "Administrator"
        password: ((DEV_BOX_PASSWORD))
    release: windows-utilities
  instances: 1
  lifecycle: service
