#!/usr/bin/env bash

# Set Pipelines
fly-envoy-nginx() {
  RED='\033[1;31m'
  NC='\033[0m' # No Color

  lpass status > /dev/null
  if [[ $? != 0 ]]; then
    echo -e "${RED}Error${NC}: You must log into lastpass before running this script."
    return
  fi

  [ "$1" == "-h" ] && echo "Push envoy-nginx pipeline to concourse" && return
  fly -t garden-windows sp -p envoy-nginx -c $HOME/workspace/garden-windows-ci/pipelines/envoy-nginx.yml \
    -l <(lpass show --notes 'Shared-Greenhouse/env-creds') \
    -l <(lpass show --notes 'Shared-Greenhouse/ci-creds') \
    -l <(lpass show --notes github-deploy-keys)
}

fly-misc() {
  RED='\033[1;31m'
  NC='\033[0m' # No Color

  lpass status > /dev/null
  if [[ $? != 0 ]]; then
    echo -e "${RED}Error${NC}: You must log into lastpass before running this script."
    return
  fi

  [ "$1" == "-h" ] && echo "Push windows-tools pipeline to concourse" && return
  fly -t garden-windows sp -p misc -c $HOME/workspace/garden-windows-ci/pipelines/misc.yml \
    -l <(lpass show --notes 'Shared-diego/garden-windows-ci-creds') \
    -l <(lpass show --notes github-deploy-keys github-deploy-keys-2 github-deploy-keys-3)
}

fly-winc() {
  RED='\033[1;31m'
  NC='\033[0m' # No Color

  lpass status > /dev/null
  if [[ $? != 0 ]]; then
    echo -e "${RED}Error${NC}: You must log into lastpass before running this script."
    return
  fi

  [ "$1" == "-h" ] && echo "Push winc pipeline to concourse" && return
  fly -t garden-windows sp -p winc -c $HOME/workspace/garden-windows-ci/pipelines/winc.yml \
    -l <(lpass show --notes 'Shared-diego/garden-windows-env-creds') \
    -l <(lpass show --notes 'Shared-diego/garden-windows-ci-creds') \
    -l <(lpass show --notes github-deploy-keys github-deploy-keys-2)
}

fly-rootfs() {
  RED='\033[1;31m'
  NC='\033[0m' # No Color

  lpass status > /dev/null
  if [[ $? != 0 ]]; then
    echo -e "${RED}Error${NC}: You must log into lastpass before running this script."
    return
  fi

  [ "$1" == "-h" ] && echo "Push rootfs pipeline to concourse" && return
  fly -t garden-windows sp -p rootfs -c $HOME/workspace/garden-windows-ci/pipelines/rootfs.yml \
    -l <(lpass show --notes 'Shared-diego/garden-windows-env-creds') \
    -l <(lpass show --notes 'Shared-diego/garden-windows-ci-creds') \
    -l <(lpass show --notes github-deploy-keys github-deploy-keys-2)
}

fly-ci () {
  RED='\033[1;31m'
  NC='\033[0m' # No Color

  lpass status > /dev/null
  if [[ $? != 0 ]]; then
    echo -e "${RED}Error${NC}: You must log into lastpass before running this script."
    return
  fi

  [ "$1" == "-h" ] && echo "Push ci pipeline to concourse" && return
  fly -t garden-windows sp -p ci -c $HOME/workspace/garden-windows-ci/pipelines/ci.yml \
  -l <(lpass show --notes 'Shared-diego/garden-windows-env-creds') \
  -l <(lpass show --notes 'Shared-diego/garden-windows-ci-creds') \
  -l <(lpass show --notes github-deploy-keys )
}
