#!/usr/bin/env bash

# git clone bbl and do latest_version=`git describe --tags $(git rev-list --tags --max-count=1)`
# Download bbl from github.com/cloudfoundry/bosh-bootloader/releases/download/$latest_version/bbl-${latest_version}_linux_x86-64
# Spit out the executable's path as output_mapping: bbl_executable

pushd bbl-repo
  latest_version=`git describe --tags $(git rev-list --tags --max-count=1)`
popd

bbl_exe_url=https://github.com/cloudfoundry/bosh-bootloader/releases/download/${latest_version}/bbl-${latest_version}_linux_x86-64
#mkdir -p binary-dir
curl -L $bbl_exe_url -o binary-dir/bbl_executable
chmod +x binary-dir/bbl_executable
echo bbl binary downloaded with version `binary-dir/bbl_executable --version`
