#!/usr/bin/env bash

set -eu

pushd src/code.cloudfoundry.org/windows-regression-tests
  cat > integration_config.json <<EOF
{
  "api": "$API",
  "admin_user": "$ADMIN_USER",
  "admin_password": "$ADMIN_PASSWORD",
  "apps_domain": "$APPS_DOMAIN",
  "num_windows_cells": $NUM_WIN_CELLS,
  "skip_ssl_validation": true,
  "isolation_segment_name": "",
  "stack": "$STACK"
}
EOF

  CONFIG=$PWD/integration_config.json ./bin/test -nodes $NODES -slowSpecThreshold=120
popd
