#!/usr/bin/env bash

set -eu

echo "Starting script"

submodule_version=$(cat windowsfs-release/src/code.cloudfoundry.org/windows2016fs/$OS_VERSION/IMAGE_TAG)
echo "in between variable definitions (submmodule_version = $submodule_version)"
blob_version=$(grep $FS_VERSION windowsfs-release/config/blobs.yml |  grep -o '[0-9]\+.[0-9]\+.[0-9]\+')

echo "Defined variables"

if [[ "$submodule_version" == "$blob_version" ]]; then
  echo "No blob to update"
else
  echo "Need to update blob"
  pushd windowsfs-release
  echo "pushed a directory"
    export GOPATH=$PWD
    mkdir -p blobs/$FS_VERSION
    echo "Made directory"
    go run src/code.cloudfoundry.org/hydrator/cmd/hydrate/main.go -image cloudfoundry/windows2016fs -outputDir blobs/$FS_VERSION -tag $submodule_version
    echo "Ran hydrator"
    bosh remove-blob "$FS_VERSION/$FS_VERSION-$blob_version.tgz"
    echo "Removed old blob"
    bosh add-blob "blobs/$FS_VERSION/$FS_VERSION-$submodule_version.tgz" "$FS_VERSION/$FS_VERSION-$submodule_version.tgz"
    echo "Added new blob"
    rm "blobs/$FS_VERSION/$FS_VERSION-$submodule_version.tgz"
  popd
fi
echo "finished"
cp -r ./windowsfs-release/. windowsfs-release-updated-blob/
echo "really finished"
