#!/usr/bin/env bash

set -eu

submodule_version=$(cat windowsfs-release/src/code.cloudfoundry.org/windows2016fs/$OS_VERSION/IMAGE_TAG)
blob_version=$(grep $FS_VERSION windowsfs-release/config/blobs.yml |  grep -o '[0-9]\+.[0-9]\+.[0-9]\+')

if [[ "$submodule_version" == "$blob_version" ]]; then
  echo "No blob to update"
else
  pushd windowsfs-release
    export GOPATH=$PWD
    mkdir -p blobs/$FS_VERSION
    go run src/code.cloudfoundry.org/hydrator/cmd/hydrate/main.go -image cloudfoundry/windows2016fs -outputDir blobs/$FS_VERSION -tag $submodule_version

    bosh remove-blob "$FS_VERSION/windows2016fs-$blob_version.tgz"
    bosh add-blob "blobs/$FS_VERSION/windows2016fs-$submodule_version.tgz" "$FS_VERSION/windows2016fs-$submodule_version.tgz"

    rm "blobs/$FS_VERSION/windows2016fs-$submodule_version.tgz"
  popd
fi

cp -r ./windowsfs-release/. windowsfs-release-updated-blob/
