#!/usr/bin/env bash

set -eu

blob_version=$(grep $FS_VERSION windowsfs-release/config/blobs.yml |  grep -o '[0-9]\+.[0-9]\+.[0-9]\+')
image_version=$(< image-version/version)

pushd windowsfs-release
  export GOPATH=$PWD
  mkdir -p blobs/$FS_VERSION
  go run ./src/code.cloudfoundry.org/hydrator/cmd/hydrate download -image cloudfoundry/windows2016fs -outputDir blobs/$FS_VERSION -tag ${image_version}

  bosh remove-blob "$FS_VERSION/windows2016fs-$blob_version.tgz"
  bosh add-blob "blobs/$FS_VERSION/windows2016fs-$submodule_version.tgz" "$FS_VERSION/windows2016fs-$submodule_version.tgz"

  rm "blobs/$FS_VERSION/windows2016fs-$submodule_version.tgz"
popd

cp -r ./windowsfs-release/. windowsfs-release-updated-blob/
