---
platform: windows

inputs:
- name: ci
- name: repo

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/ginkgo-to-gopath-windows/run.ps1
  path: powershell
  args:
  - "/C"
  - "mkdir $env:TMP -ea 0"

params:
  IMPORT_PATH:
  NODES: 4
  TMP:
  TEMP:
