---
platform: windows

inputs:
- name: ci
- name: repo

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/ginkgo-to-gopath-windows/run.ps1

params:
  IMPORT_PATH:
  NODES: 4
  TMP: "C:\\var\\vcap\\data\\tmp"
  GOTMPDIR: "C:\\var\\vcap\\data\\tmp"
  TEMP: "C:\\var\\vcap\\data\\tmp"
