#!/usr/bin/env bash

set -eu

ops="
---
- type: replace
  path: /stemcells/alias=windows/version
  value: "$(< windows-stemcell/version)"

- type: replace
  path: /releases/name=concourse
  value:
    name: concourse
    sha1: "$(< concourse-release/sha1)"
    url: "$(< concourse-release/url)"
    version: "$(< concourse-release/version)"

- type: replace
  path: /releases/name=windows-tools
  value:
    name: windows-tools
    sha1: "$(< windows-tools-release/sha1)"
    url: "$(< windows-tools-release/url)"
    version: "$(< windows-tools-release/version)"

- type: replace
  path: /releases/name=windows-utilities
  value:
    name: windows-utilities
    sha1: "$(< windows-utilities-release/sha1)"
    url: "$(< windows-utilities-release/url)"
    version: "$(< windows-utilities-release/version)"
"

echo "$ops"

eval "$(bbl --state-dir=garden-windows-environments/spitfire print-env)"
bosh -d ${BOSH_DEPLOYMENT} manifest > artifacts/manifest.yml.OLD
bosh int artifacts/manifest.yml.OLD -o <(echo "${ops}") > artifacts/manifest.yml

echo "deployment: ${BOSH_DEPLOYMENT}" > artifacts/source-file.yml
echo "${BOSH_CREDENTIALS}" >> artifacts/source-file.yml
