#!/usr/bin/env bash

set -eu

ops="
---
- type: replace
  path: /stemcells/alias=windows/version
  value: "$(< windows-stemcell/version)"

- type: replace
  path: /releases/name=windows-tools
  value:
    name: windows-tools
    sha1:
    url:
    version:
"

eval "$(bbl --state-dir=garden-windows-environments/spitfire print-env)"
bosh -d ${BOSH_DEPLOYMENT} manifest > artifacts/manifest.yml.OLD
bosh int artifacts/manifest.yml.OLD -o <(echo "${ops}") > artifacts/manifest.yml

echo "deployment: ${BOSH_DEPLOYMENT}" > artifacts/source-file.yml
echo "${BOSH_CREDENTIALS}" >> artifacts/source-file.yml
