---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/garden-windows-ci

inputs:
- name: ci  # - This repo
- name: bbl-state  # - The env repo containing the Director's bbl state dir

outputs:
- name: source-file
# - The bbl-state resource, with changes git committed,
# - ready to be `put` to a git resource.
# - This output _must_ be persisted for these tasks to function properly

params:
  BBL_STATE_DIR: bbl-state
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to the `bbl-state` input
  # - If blank or '.', uses `bbl-state` input as the location for bbl state
  # - If the specified path does not exist, it will be created

run:
  path: ci/tasks/create-bosh-deployment-resource-source-file/task
