#!/bin/bash -e

main() {
  ROOT_DIR="${1}"

  pushd "${ROOT_DIR}/bbl-state/${BBL_STATE_DIR}"
    eval "$(bbl print-env)"

    local source_file
    source_file="source_file"

    local jumpbox_url
    jumpbox_url=$(bbl jumpbox-address)

    echo "client: $BOSH_CLIENT" > "${source_file}"
    echo "client_secret: $BOSH_CLIENT_SECRET" >> "${source_file}"
    echo "target: $BOSH_ENVIRONMENT" >> "${source_file}"
    echo "ca_cert: $BOSH_CA_CERT" >> "${source_file}"
    echo "jumpbox_ssh_key: $JUMPBOX_PRIVATE_KEY" >> "${source_file}"
    echo "jumpbox_url: $jumpbox_url" >> "${source_file}"
    echo "jumpbox_username: jumpbox" >> "${source_file}"
  popd
}

main ${PWD}
