#!/usr/bin/env bash

set -eux

version=$(bosh int --path '/stemcells/os=ubuntu-bionic/version' $bosh_manifest_path)
cd stemcell
curl -L "https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-bionic-go_agent?v=${version}" -o "light-bosh-stemcell-${version}-google-kvm-ubuntu-xenial-go_agent.tgz"
