#!/usr/bin/env bash

set -e

pushd windowsfs-release
  ./scripts/create-release --tarball ../release-tarball/release.tgz --timestamp-version
  echo "release.tgz" > ../release-tarball/name
  mkdir ../release-tarball/config
  cp config/final.yml ../release-tarball/config
popd
