#!/usr/bin/env bash

set -e

pushd windowsfs-release
  ./scripts/create-release --tarball ../release-tarball/release.tgz --timestamp-version
popd

echo "$(grep "^name:" config/final.yml  | awk '{print $2}')" > ../release-tarball/name
