---
platform: windows

inputs:
- name: ci
- name: containerd-fork
  path: src/github.com/containerd/containerd

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/test-containerd/run.ps1
