#!/usr/bin/env bash

set -eu

export GOPATH=$(cd "$GOPATH" && pwd)
export PATH="$PATH:$GOPATH/bin"

go install github.com/onsi/ginkgo/v2/ginkgo@latest

pushd repo
  ginkgo -p -r -race -keep-going -randomize-suites -skip-package "$IGNORE_PACKAGES" "$TEST_PATH"
popd
