#!/bin/sh

set -eu

# convert files written on Windows OS originally
dos2unix kb-metadata/kb-metadata

blob_version=$(grep $FS_VERSION windowsfs-release/config/blobs.yml |  grep -o '[0-9]\+.[0-9]\+.[0-9]\+')

cat > generated-notes/release-notes <<EOF
### windows2016fs changes
* Includes ${blob_version} of cloudfoundry/windows2016fs

\`\`\`
$(< kb-metadata/kb-metadata)
\`\`\`
EOF
