---
platform: linux

image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}

inputs:
  - name: ci
  - name: rootfs-metadata
  - name: all-kbs-list

outputs:
  - name: generated-notes

run:
  path: ci/tasks/generate-release-notes/run
