#!/bin/bash
set -o errexit
set -o pipefail

: ${ADMIN_PASSWORD:?"!"}
: ${ADMIN_USER:?"!"}
: ${API:?"!"}
: ${APPS_DOMAIN:?"!"}
: ${NUM_WINDOWS_CELLS:?"!"}
: ${WINDOWS_SECURE_ADDRESS:?"!"}
: ${WINDOWS_STACK:?"!"}

: ${CREDHUB_MODE:=""}
: ${CREDHUB_SECRET:=""}

read -r -d '' JSON_TEMPLATE <<EOF || true {
  "api": "$API",
  "apps_domain": "$APPS_DOMAIN",
  "admin_user": "$ADMIN_USER",
  "admin_password": "$ADMIN_PASSWORD",
  "skip_ssl_validation": true,
  "use_http": true,
  "backend": "diego",
  "include_windows": true,
  "include_ssh": true,
  "windows_test_task": true,
  "credhub_mode": "$CREDHUB_MODE",
  "credhub_secret": "$CREDHUB_SECRET",
  "windows_secure_address: "$WINDOWS_SECURE_ADDRESS",
  "num_windows_cells: "$NUM_WINDOWS_CELLS",
  "use_windows_test_task: true,
  "use_windows_context_path: true,
  "windows_stack: "$WINDOWS_STACK"
}
EOF

echo "$JSON_TEMPLATE" > integration-config/integration-config.json
