#!/bin/bash
set -o errexit
set -o pipefail

: ${ADMIN_PASSWORD:?"!"}
: ${ADMIN_USER:?"!"}
: ${API:?"!"}
: ${APPS_DOMAIN:?"!"}
: ${UNALLOCATED_IP:?"!"}
: ${WINDOWS_STACK:?"!"}

: ${CREDHUB_MODE:=""}
: ${CREDHUB_SECRET:=""}

read -r -d '' JSON_TEMPLATE <<EOF || true
{
  "api": "$API",
  "apps_domain": "$APPS_DOMAIN",
  "admin_user": "$ADMIN_USER",
  "admin_password": "$ADMIN_PASSWORD",
  "skip_ssl_validation": true,
  "include_apps": false,
  "include_detect": false,
  "include_persistent_app": false,
  "include_routing": false,
  "include_v3": false,
  "include_capi_no_bridge": false,
  "use_http": true,
  "include_windows": true,
  "include_ssh": true,
  "credhub_mode": "$CREDHUB_MODE",
  "credhub_client": "credhub_admin_client",
  "credhub_secret": "$CREDHUB_SECRET",
  "unallocated_ip_for_security_group": "$UNALLOCATED_IP",
  "use_windows_test_task": true,
  "use_windows_context_path": true,
  "windows_stack": "$WINDOWS_STACK"
}
EOF

echo "$JSON_TEMPLATE" > integration-config/integration_config.json
