#!/usr/bin/env bash

set -e

function cleanup() { eval "$(ssh-agent -k)"; }
eval $(ssh-agent -s)
trap cleanup EXIT

ssh-keyscan github.com > ~/.ssh/known_hosts
echo "$GIT_PRIVATE_KEY" | ssh-add -

tag="${TAG_PREFIX}$(< version_dir/number)"

cd repo

git push --delete origin "${tag}"