#!/usr/bin/env bash

set -eu

version=$(cat windowsfs-online-release-version/number)
notes=$(cat kb-metadata/kb-metadata | cut -d ' ' -f 1,2,3,4)

payload="The following *2 rootfs (v${version})* releases just shipped:
- https://github.com/cloudfoundry/windowsfs-online-release/releases/tag/v${version}
- https://github.com/cloudfoundry/windows2019fs-release/releases/tag/v${version}

\`\`\`
${notes}
\`\`\`
"

curl \
  -X POST \
  --data-urlencode "payload={\"channel\": \"#${CHANNEL}\", \"text\": \"${payload}\", \"icon_emoji\": \":robot_face:\"}" \
  ${SLACK_URL}
