#!/usr/bin/env bash

set -eu

version=$(< windowsfs-online-release-version/number)
notes=$(< generated-notes/release-notes)
payload="The following *2 rootfs* releases just shipped:
- https://github.com/cloudfoundry/windowsfs-online-release/releases/tag/v${version}
- https://github.com/cloudfoundry/windows2019fs-release/releases/tag/v${version}

${notes}

${USERS}
"

curl \
  -X POST \
  --data-urlencode "payload={\"channel\": \"#${CHANNEL}\", \"text\": \"${payload}\", \"icon_emoji\": \":robot_face:\"}" \
  ${SLACK_URL}
