---
- type: replace
  path: /instance_groups/name=windows2019-cell/jobs/name=route_emitter_windows/properties/tcp?/enabled
  value: true

- type: replace
  path: /instance_groups/name=windows2019-cell/jobs/name=route_emitter_windows/properties/uaa?/client_secret
  value: ((uaa_clients_tcp_emitter_secret))

- type: replace
  path: /instance_groups/name=windows2019-cell/jobs/name=route_emitter_windows/properties/uaa?/ca_cert
  value: ((uaa_ssl.ca))

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/app_domains/-
  value:
     name: ((tcp_domain))
     router_group_name: ((tcp_router_group))
