---
platform: windows

inputs:
- name: ci

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/verify-iwa-functionality/run.ps1

params:
  IWA_TEST_APP_ROUTE:
  IWA_DOMAIN:
  IWA_USERNAME:
  IWA_PASSWORD:
