#!/bin/bash
set -e

PRIVATE_YML='---
blobstore:
  provider: s3
  options:
    credentials_source: env_or_profile'
echo "$PRIVATE_YML" > release-repo/config/private.yml

bosh vendor-package --dir release-repo $PACKAGE package-repo

cp -r release-repo bumped-release-repo
