#!/bin/bash
set -e

PRIVATE_YML='---
blobstore:
  provider: s3
  options:
    credentials_source: env_or_profile'
echo "$PRIVATE_YML" > release-repo/config/private.yml

bosh vendor-package --dir release-repo $PACKAGE package-repo

pushd release-repo
  git submodule update --recursive --remote --force

  if [ -n "$(git status --porcelain)" ]; then
    git config user.email "pivotal-netgarden-eng@pivotal.io"
    git config user.name "CI (Automated)"
    git add .
    git commit -m "Bump $PACKAGE"
  fi
popd

cp -r release-repo/. bumped-release-repo/
