#!/usr/bin/env bash

set -eu

version=$(cat version/version)

pushd ci/tasks/create-rootfs-tracker-story
  bundle install
  bundle exec ./create-story $TRACKER_TOKEN $TRACKER_PROJECT_ID $version $FS_VERSION
popd
