#!/usr/bin/env bash

set -eu

export PATH="$PATH:~/go/bin"

go get github.com/onsi/ginkgo/ginkgo

ginkgo -p -r -race -keepGoing -randomizeSuites -skipPackage "$IGNORE_PACKAGES" src/code.cloudfoundry.org/hydrator
