---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

inputs:
- name: slack-delegate-bot
- name: config
- name: ci

outputs:
- name: app

run:
  path: ci/tasks/deploy-delegate-bot/run
