---
platform: windows

inputs:
- name: ci
- name: repo

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/ginkgo-test-windows/run.ps1

params:
  TEST_PATH:
  NODES: 4
  EPHEMERAL_DISK_TEMP_PATH: