---
platform: windows

inputs:
- name: ci
- name: version
- name: repo

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/docker-build/run.ps1

params:
  DOCKERFILE: ""
  IMAGE_NAME: ""
  DOCKER_USERNAME: ""
  DOCKER_PASSWORD: ""
  EPHEMERAL_DISK_TEMP_PATH:
