#!/usr/bin/env bash

set -ex

pushd source-repo
  go get $DEP
  go mod vendor

  if [ -n "$(git status --porcelain)" ]; then
    git config user.email "pivotal-netgarden-eng@pivotal.io"
    git config user.name "CI (Automated)"
    git add -A .
    git commit -m "Bump $DEP package"
  fi
popd

cp -r source-repo bumped-repo/
