#!/usr/bin/env bash

set -ex

export GOPATH=$PWD

mkdir -p "src/$SOURCE_IMPORT_PATH"
cp -r source-repo/. "src/$SOURCE_IMPORT_PATH"

pushd "src/$SOURCE_IMPORT_PATH"
  dep ensure -update $DEP
  if [ -n "$(git status --porcelain)" ]; then
    git config user.email "pivotal-netgarden-eng@pivotal.io"
    git config user.name "CI (Automated)"
    git add -A .
    git commit -m "Bump $DEP package"
  fi
popd

cp -r "src/$SOURCE_IMPORT_PATH/." bumped-repo/
