---
platform: linux

image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}

inputs:
- name: ci
- name: release-tarball

outputs:
- name: windowsfs-opsfile

params:
  FS_VERSION:
  CELL_NAME:

run:
  path: ci/tasks/write-versioned-windows2016fs-opsfile/run
