---
platform: windows

inputs:
  - name: ci
  - name: winc-release

outputs:
  - name: generated-readme

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/winc-release-readme/run.ps1
  path: powershell
  args:
  - "/C"
  - "mkdir $env:TMP -ea 0"

params:
  WINC_TEST_ROOTFS:
  GROOT_IMAGE_STORE:
  TMP:
  TEMP:
