---
platform: windows

inputs:
- name: ci
- name: winc
- name: groot-binary

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/test-winc-wip/run.ps1

params:
  WINC_TEST_ROOTFS:
  WINC_TEST_PERF_CONCURRENT_CONTAINERS: 15
  WINDOWS_VERSION:
