#!/usr/bin/env bash

set -eu

# Get version from latest github release so it's accurate.
version="$(curl --silent https://api.github.com/repos/cloudfoundry/windows-tools-release/releases/latest | jq -r .tag_name | cut -d"v" -f2)"

# For windows-tools-release, we only increment major.
bumpedVersion=$((version+1))

echo "v$bumpedVersion" > github-release-info/version
echo "Windows tools v$bumpedVersion" > github-release-info/name

pushd windows-tools-release
  PRIVATE_YML='---
  blobstore:
    provider: s3
    options:
      credentials_source: env_or_profile'
  echo "$PRIVATE_YML" > config/private.yml

  bosh create-release --final --version $bumpedVersion

  git config user.email "pivotal-netgarden-eng@pivotal.io"
  git config user.name "CI (Automated)"
  git add .
  git commit -m "Create release $bumpedVersion"
popd

cp -r windows-tools-release/. windows-tools-release-bumped/
