resource_types:
- name: metalink-repository
  source:
    repository: dpb587/metalink-repository-resource
  type: docker-image

resources:
- name: cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    organization: garden-windows
    space: topic-bots
    username: ((cf-username))
    password: ((cf-password))
- name: config
  type: git
  source:
    uri: https://github.com/greenhouse-org/delegate-bot-config.git
    branch: garden-windows
- name: tracker-bot-repo
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/relint-trackerbot.git
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
- name: slack-delegate-bot
  type: metalink-repository
  source:
    include_files:
    - delegatebot-*-linux-amd64
    uri: git+https://github.com/dpb587/slack-delegate-bot.git//published#artifacts

jobs:
- name: deploy-tracker-bot
  serial: true
  plan:
  - get: tracker-bot-repo
  - task: write-config-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/garden-windows-ci
      inputs:
      - name: tracker-bot-repo
      outputs:
      - name: tracker-bot-repo
      params:
        TRACKER_API_TOKEN: ((tracker-api-token))
        TRACKER_PROJECT_ID: 2409722
      run:
        path: bash
        args:
        - -c
        - |
          cat > tracker-bot-repo/config.yml <<EOF
          ignore:
          - envoy-windows-*
          - bbl-down-*
          groups: {}
          EOF

          cat > tracker-bot-repo/manifest.yml <<EOF
          applications:
          - name: windows-containers-tracker-bot
            health-check-type: none
            command: relint-trackerbot --config-file config.yml
            buildpack: go_buildpack
            no-route: true
            env:
              GOVERSION: go1.13
              GOPACKAGENAME: github.com/pivotal-cf-experimental/relint-trackerbot
              CONCOURSE_HOST: https://garden-windows.ci.cf-app.com
              CONCOURSE_TEAM: main
              TRACKER_API_TOKEN: ${TRACKER_API_TOKEN}
              TRACKER_PROJECT_ID: ${TRACKER_PROJECT_ID}
          EOF
  - put: cf
    inputs:
    - tracker-bot-repo
    params:
      manifest: tracker-bot-repo/manifest.yml
      path: tracker-bot-repo


- name: deploy-slack-delegate-bot
  serial: true
  plan:
  - in_parallel:
    - get: slack-delegate-bot
      trigger: true
    - get: config
      trigger: true
  - task: build
    config:
      container_limits: {}
      image_resource:
        source:
          repository: alpine
        type: docker-image
      inputs:
      - name: slack-delegate-bot
      - name: config
      outputs:
      - name: app
      platform: linux
      run:
        args:
        - -c
        - |
          set -eu

          # required when running the bot for user timezone configuration
          apk add --no-cache tzdata

          # avoids google default credentials error during validation
          export PAIRIST_API_KEY=fake-token

          cp slack-delegate-bot/* app/exec
          echo 'exec ./exec --config=config/*.yml --config=config/default.delegatebot ${COMMAND:-run}' > app/run.sh
          chmod +x app/*

          cat > app/cf.yml <<EOF
          applications:
          - name: garden-windows-slack-delegate-bot
            memory: 32M
            instances: 1
            buildpack: binary_buildpack
            env:
              SLACK_TOKEN: ((slack-token))
            no-route: true
            command: ./run.sh
          EOF

          cp -rp config/config app/config

          cd app

          COMMAND=validate ./run.sh
        path: sh
  - put: cf
    params:
      manifest: app/cf.yml
      path: app
