resource_types:
- name: metalink-repository
  source:
    repository: dpb587/metalink-repository-resource
  type: docker-image

resources:
- name: cf
  source:
    api: https://api.run.pivotal.io
    organization: garden-windows
    password: ((cf-password))
    space: topic-bots
    username: ((cf-username))
  type: cf
- name: config
  source:
    branch: garden-windows
    private_key: null
    uri: https://github.com/greenhouse-org/delegate-bot-config.git
  type: git
- name: slack-delegate-bot
  source:
    include_files:
    - delegatebot-*-linux-amd64
    uri: git+https://github.com/dpb587/slack-delegate-bot.git//published#artifacts
  type: metalink-repository

jobs:
- name: deploy
  plan:
  - aggregate:
    - get: slack-delegate-bot
      trigger: true
    - get: config
      trigger: true
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: alpine
        type: docker-image
      inputs:
      - name: slack-delegate-bot
      - name: config
      outputs:
      - name: app
      platform: linux
      run:
        args:
        - -c
        - |
          set -eu

          # required when running the bot for user timezone configuration
          apk add --no-cache tzdata

          # avoids google default credentials error during validation
          export PAIRIST_API_KEY=fake-token

          cp slack-delegate-bot/* app/exec
          echo 'exec ./exec --config=config/*.yml --config=config/default.delegatebot ${COMMAND:-run}' > app/run.sh
          chmod +x app/*

          cat > app/cf.yml <<EOF
          applications:
          - name: garden-windows-slack-delegate-bot
            memory: 32M
            instances: 1
            buildpack: binary_buildpack
            env:
              SLACK_TOKEN: ((slack-token))
            no-route: true
            command: ./run.sh
          EOF

          cp -rp config/config app/config

          cd app

          COMMAND=validate ./run.sh
        path: sh
    task: build
  - params:
      manifest: app/cf.yml
      path: app
    put: cf
  serial: true
