resource_types:
- name: metalink-repository
  type: docker-image
  source:
    repository: dpb587/metalink-repository-resource

resources:
- name: cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    organization: garden-windows
    space: topic-bots
    username: ((cf-username))
    password: ((cf-password))
- name: config
  type: git
  source:
    uri: https://github.com/greenhouse-org/delegate-bot-config.git
    branch: garden-windows
- name: ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/garden-windows-ci
- name: slack-delegate-bot
  type: metalink-repository
  source:
    include_files:
    - delegatebot-*-linux-amd64
    uri: git+https://github.com/dpb587/slack-delegate-bot.git//published#artifacts

jobs:
- name: deploy-slack-delegate-bot
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: slack-delegate-bot
      trigger: true
    - get: config
      trigger: true
  - task: build
    file: ci/tasks/deploy-delegate-bot/task.yml
    params:
      SLACK_TOKEN: ((slack-token))
  - put: cf
    params:
      manifest: app/cf.yml
      path: app
