resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: ci
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/garden-windows-ci.git

- name: windows-2019-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-windows2019-go_agent

- name: windows-tools-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/windows-tools-release

- name: windows-utilities-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/windows-utilities-release

- name: concourse-release
  type: bosh-io-release
  source:
    repository: concourse/concourse-bosh-release

- name: concourse-deployment
  type: bosh-deployment
  source:
    skip_check: true

- name: garden-windows-environments
  type: git
  source:
    uri: git@github.com:pivotal/garden-windows-environments
    branch: master
    private_key: ((TAS-RUNTIME-GITHUB_PRIVATE_KEY))

jobs:
- name: update-concourse
  serial: true
  serial_groups: [ deploy ]
  plan:
  - in_parallel:
    - get: ci
    - get: garden-windows-environments
    - get: windows-2019-stemcell
      trigger: true
    - get: concourse-release
      params: {tarball: false}
      trigger: true
    - get: windows-tools-release
      params: {tarball: false}
      trigger: true
    - get: windows-utilities-release
      params: {tarball: false}
      trigger: true
  - task: update-concourse-manifest
    file: ci/tasks/update-windows-worker-manifest/task.yml
    input_mapping:
      windows-stemcell: windows-2019-stemcell
    params:
      BOSH_DEPLOYMENT: concourse
      BOSH_CREDENTIALS: ((spitfire-bosh-credentials))
  - try:
      put: concourse-deployment
      inputs:
      - windows-2019-stemcell
      - artifacts
      params:
        source_file: artifacts/source-file.yml
        manifest: artifacts/manifest.yml
        stemcells:
          - windows-2019-stemcell/stemcell.tgz
