resources:
- name: twice-a-week
  type: time
  source:
    days: [Sunday, Wednesday]
    start: 01:00  # 8PM ET
    stop:  02:00  # 9PM ET

- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/garden-windows-ci.git

- name: bosh-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-deployment.git

- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: garden-windows-environments
  type: git
  source:
    branch: master
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    uri: git@github.com:pivotal/garden-windows-environments

# Lock Pools

- name: alfredo-lock-pool
  type: pool
  source:
    branch: master
    pool: alfredo
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    uri: git@github.com:greenhouse-ci/locks

- name: sriracha-lock-pool
  type: pool
  source:
    branch: master
    pool: sriracha
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    uri: git@github.com:greenhouse-ci/locks

- name: aioli-lock-pool
  type: pool
  source:
    branch: master
    pool: aioli
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    uri: git@github.com:greenhouse-ci/locks

- name: hummus-lock-pool
  type: pool
  source:
    branch: master
    pool: hummus
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    uri: git@github.com:greenhouse-ci/locks

- name: guac-lock-pool
  type: pool
  source:
    branch: master
    pool: guac
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    uri: git@github.com:greenhouse-ci/locks

- name: mulgore-lock-pool
  type: pool
  source:
    branch: master
    pool: mulgore
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    uri: git@github.com:greenhouse-ci/locks

- name: pesto-lock-pool
  type: pool
  source:
    branch: master
    pool: pesto
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    uri: git@github.com:greenhouse-ci/locks

- name: spitfire-lock-pool
  type: pool
  source:
    branch: master
    pool: spitfire
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    uri: git@github.com:greenhouse-ci/locks

- name: tartar-lock-pool
  type: pool
  source:
    branch: master
    pool: tartar
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    uri: git@github.com:greenhouse-ci/locks

jobs:
- name: alfredo-cleanup
  serial: true
  plan:
  - in_parallel:
    - get: twice-a-week
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
    - get: ci
  - put: alfredo-lock-pool
    params:
      acquire: true
  - task: clean-up
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    params:
      BBL_STATE_DIR: alfredo
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: alfredo-lock-pool
      params:
        release: alfredo-lock-pool
  - task: upload-bosh-dns-release
    file: ci/tasks/bosh-upload-release/task.yml
    params:
      BBL_STATE_DIR: alfredo
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      put: alfredo-lock-pool
      params:
        release: alfredo-lock-pool

- name: hummus-cleanup
  serial: true
  plan:
  - in_parallel:
    - get: twice-a-week
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
    - get: ci
  - put: hummus-lock-pool
    params:
      acquire: true
  - task: clean-up
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    params:
      BBL_STATE_DIR: hummus
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: hummus-lock-pool
      params:
        release: hummus-lock-pool
  - task: upload-bosh-dns-release
    file: ci/tasks/bosh-upload-release/task.yml
    params:
      BBL_STATE_DIR: hummus
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      put: hummus-lock-pool
      params:
        release: hummus-lock-pool

- name: pesto-cleanup
  serial: true
  plan:
  - in_parallel:
    - get: twice-a-week
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
    - get: ci
  - put: pesto-lock-pool
    params:
      acquire: true
  - task: clean-up
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    params:
      BBL_STATE_DIR: pesto
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: pesto-lock-pool
      params:
        release: pesto-lock-pool
  - task: upload-bosh-dns-release
    file: ci/tasks/bosh-upload-release/task.yml
    params:
      BBL_STATE_DIR: pesto
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      put: pesto-lock-pool
      params:
        release: pesto-lock-pool

- name: spitfire-cleanup
  serial: true
  plan:
  - in_parallel:
    - get: twice-a-week
      trigger: true
    - get: ci
  - put: spitfire-lock-pool
    params:
      acquire: true
  - task: clean-up
    file: ci/tasks/bosh-cleanup/task.yml
    params:
      BOSH_CLIENT: ((SPITFIRE_BOSH_CLIENT))
      BOSH_CLIENT_SECRET: ((SPITFIRE_BOSH_CLIENT_SECRET))
      BOSH_ENVIRONMENT: ((SPITFIRE_BOSH_ENVIRONMENT))
      BOSH_CA_CERT: ((SPITFIRE_BOSH_CA_CERT))
      JUMPBOX_IP: ((SPITFIRE_JUMPBOX_IP))
      JUMPBOX_SSH_KEY: ((SPITFIRE_JUMPBOX_SSH_KEY))
    ensure:
      put: spitfire-lock-pool
      params:
        release: spitfire-lock-pool

- name: tartar-cleanup
  serial: true
  plan:
  - in_parallel:
    - get: twice-a-week
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
    - get: ci
  - put: tartar-lock-pool
    params:
      acquire: true
  - task: clean-up
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    params:
      BBL_STATE_DIR: tartar
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: tartar-lock-pool
      params:
        release: tartar-lock-pool
  - task: upload-bosh-dns-release
    file: ci/tasks/bosh-upload-release/task.yml
    params:
      BBL_STATE_DIR: tartar
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      put: tartar-lock-pool
      params:
        release: tartar-lock-pool

- name: sriracha-cleanup
  serial: true
  plan:
  - in_parallel:
    - get: twice-a-week
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
    - get: ci
  - put:  sriracha-lock-pool
    params:
      acquire: true
  - task: clean-up
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    params:
      BBL_STATE_DIR:  sriracha
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: sriracha-lock-pool
      params:
        release: sriracha-lock-pool
  - task: upload-bosh-dns-release
    file: ci/tasks/bosh-upload-release/task.yml
    params:
      BBL_STATE_DIR: sriracha
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      put: sriracha-lock-pool
      params:
        release: sriracha-lock-pool

- name: aioli-cleanup
  serial: true
  plan:
  - in_parallel:
    - get: twice-a-week
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
    - get: ci
  - put: aioli-lock-pool
    params:
      acquire: true
  - task: clean-up
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    params:
      BBL_STATE_DIR: aioli
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: aioli-lock-pool
      params:
        release: aioli-lock-pool
  - task: upload-bosh-dns-release
    file: ci/tasks/bosh-upload-release/task.yml
    params:
      BBL_STATE_DIR: aioli
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      put: aioli-lock-pool
      params:
        release: aioli-lock-pool

- name: guac-cleanup
  serial: true
  plan:
  - in_parallel:
    - get: twice-a-week
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
    - get: ci
  - put: guac-lock-pool
    params:
      acquire: true
  - task: clean-up
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    params:
      BBL_STATE_DIR: guac
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: guac-lock-pool
      params:
        release: guac-lock-pool
  - task: upload-bosh-dns-release
    file: ci/tasks/bosh-upload-release/task.yml
    params:
      BBL_STATE_DIR: guac
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      put: guac-lock-pool
      params:
        release: guac-lock-pool

- name: mulgore-cleanup
  serial: true
  plan:
  - in_parallel:
    - get: twice-a-week
      trigger: true
      tags: [vsphere]
    - get: ci
      tags: [vsphere]
    - get: bosh-deployment
      tags: [vsphere]
  - put: mulgore-lock-pool
    params:
      acquire: true
  - task: clean-up
    file: ci/tasks/bosh-cleanup/task.yml
    tags: [vsphere]
    params:
      BOSH_CLIENT: ((MULGORE_BOSH_CLIENT))
      BOSH_CLIENT_SECRET: ((MULGORE_BOSH_CLIENT_SECRET))
      BOSH_ENVIRONMENT: ((MULGORE_BOSH_ENVIRONMENT))
      BOSH_CA_CERT: ((MULGORE_BOSH_CA_CERT))
      JUMPBOX_IP: ((MULGORE_JUMPBOX_IP))
      JUMPBOX_SSH_KEY: ((MULGORE_JUMPBOX_SSH_KEY))
    on_failure:
      put: mulgore-lock-pool
      params:
        release: mulgore-lock-pool
  - task: update-runtime-config-dns
    file: ci/tasks/bosh-update-runtime-config-dns/task.yml
    tags: [vsphere]
    params:
      BOSH_CLIENT: ((MULGORE_BOSH_CLIENT))
      BOSH_CLIENT_SECRET: ((MULGORE_BOSH_CLIENT_SECRET))
      BOSH_ENVIRONMENT: ((MULGORE_BOSH_ENVIRONMENT))
      BOSH_CA_CERT: ((MULGORE_BOSH_CA_CERT))
      JUMPBOX_IP: ((MULGORE_JUMPBOX_IP))
      JUMPBOX_SSH_KEY: ((MULGORE_JUMPBOX_SSH_KEY))
    ensure:
      put: mulgore-lock-pool
      params:
        release: mulgore-lock-pool
