groups:
- name: bbl-up
  jobs:
    - bbl-update-hummus
    - bbl-update-tzatziki
    - bbl-update-aioli
    - bbl-update-pesto
    - bbl-update-sriracha
    - bbl-update-guac
- name: bbl-down
  jobs:
    - bbl-down-hummus
    - bbl-down-tzatziki
    - bbl-down-aioli
    - bbl-down-pesto
    - bbl-down-sriracha
    - bbl-down-guac

resources:
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: sophiewigmore-cdct
  type: git
  source:
    branch: delete-deployments
    uri: https://github.com/sophiewigmore/cf-deployment-concourse-tasks.git

- name: hummus-lock-pool
  type: pool
  source:
    branch: master
    pool: hummus
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

- name: guac-lock-pool
  type: pool
  source:
    branch: master
    pool: guac
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

- name: tzatziki-lock-pool
  type: pool
  source:
    branch: master
    pool: tzatziki
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

- name: aioli-lock-pool
  type: pool
  source:
    branch: master
    pool: aioli
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

- name: pesto-lock-pool
  type: pool
  source:
    branch: master
    pool: pesto
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

- name: sriracha-lock-pool
  type: pool
  source:
    branch: master
    pool: sriracha
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

- name: garden-windows-environments
  type: git
  source:
    branch: master
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:pivotal/garden-windows-environments

- name: sunday-morning
  type: time
  source:
    days: [Sunday]
    start: 12:00 AM
    stop: 1:00 AM

jobs:
- name: bbl-update-hummus
  serial: true
  serial_groups: [update]
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: hummus-lock-pool
    - get: garden-windows-environments
    - get: sunday-morning
      trigger: true
  - put: hummus-lock-pool
    timeout: 1m
    params:
      acquire: true
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_GCP_REGION: us-east1
      BBL_STATE_DIR: hummus
      BBL_LB_CERT: cert.pem
      BBL_LB_KEY: key.pem
      LB_DOMAIN: hummus.cf-app.com
      BBL_ENV_NAME: hummus
    input_mapping:
      bbl-state: garden-windows-environments
      bbl-config: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: hummus-lock-pool
        params:
          release: hummus-lock-pool

- name: bbl-update-guac
  serial: true
  serial_groups: [update]
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: guac-lock-pool
    - get: garden-windows-environments
    # - get: sunday-morning
    #   trigger: true
  - put: guac-lock-pool
    timeout: 1m
    params:
      acquire: true
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: aws
      BBL_AWS_ACCESS_KEY_ID: {{GUAC_AWS_ACCESS_KEY_ID}}
      BBL_AWS_SECRET_ACCESS_KEY: {{GUAC_AWS_SECRET_ACCESS_KEY}}
      BBL_AWS_REGION: us-east-1
      BBL_STATE_DIR: guac
      BBL_LB_CERT: certs/cert.pem
      BBL_LB_KEY: certs/key.pem
      LB_DOMAIN: guac.cf-app.com
      BBL_ENV_NAME: guac
    input_mapping:
      bbl-state: garden-windows-environments
      bbl-config: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: guac-lock-pool
        params:
          release: guac-lock-pool

- name: bbl-update-tzatziki
  serial: true
  serial_groups: [update]
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: tzatziki-lock-pool
    - get: garden-windows-environments
    # - get: sunday-morning
    #   trigger: true
  - put: tzatziki-lock-pool
    timeout: 1m
    params:
      acquire: true
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_GCP_REGION: us-east1
      BBL_STATE_DIR: tzatziki
      BBL_LB_CERT: certs/cert.pem
      BBL_LB_KEY: certs/key.pem
      LB_DOMAIN: tzatziki.cf-app.com
      BBL_ENV_NAME: tzatziki
    input_mapping:
      bbl-state: garden-windows-environments
      bbl-config: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: tzatziki-lock-pool
        params:
          release: tzatziki-lock-pool

- name: bbl-update-aioli
  serial: true
  serial_groups: [update]
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: aioli-lock-pool
    - get: garden-windows-environments
    - get: sunday-morning
      trigger: true
  - put: aioli-lock-pool
    timeout: 1m
    params:
      acquire: true
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_GCP_REGION: us-east1
      BBL_STATE_DIR: aioli
      BBL_LB_CERT: cert.pem
      BBL_LB_KEY: key.pem
      LB_DOMAIN: aioli.cf-app.com
      BBL_ENV_NAME: aioli
    input_mapping:
      bbl-state: garden-windows-environments
      bbl-config: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: aioli-lock-pool
        params:
          release: aioli-lock-pool

- name: bbl-update-pesto
  serial: true
  serial_groups: [update]
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: pesto-lock-pool
    - get: garden-windows-environments
    # - get: sunday-morning
    #   trigger: true
  - put: pesto-lock-pool
    timeout: 1m
    params:
      acquire: true
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: azure
      BBL_AZURE_CLIENT_ID:
      BBL_AZURE_CLIENT_SECRET:
      BBL_AZURE_TENANT_ID:
      BBL_AZURE_SUBSCRIPTION_ID:
      BBL_AZURE_REGION:
      BBL_STATE_DIR: pesto
      BBL_LB_CERT: cert.pem
      BBL_LB_KEY: key.pem
      LB_DOMAIN: pesto.cf-app.com
      BBL_ENV_NAME: pesto
    input_mapping:
      bbl-state: garden-windows-environments
      bbl-config: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: pesto-lock-pool
        params:
          release: pesto-lock-pool

- name: bbl-update-sriracha
  serial: true
  serial_groups: [update]
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: sriracha-lock-pool
    - get: garden-windows-environments
    # - get: sunday-morning
    #   trigger: true
  - put: sriracha-lock-pool
    timeout: 1m
    params:
      acquire: true
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_GCP_REGION: us-central1
      BBL_STATE_DIR: sriracha
      BBL_LB_CERT: certs/cert.pem
      BBL_LB_KEY: certs/key.pem
      LB_DOMAIN: sriracha.cf-app.com
      BBL_ENV_NAME: sriracha
    input_mapping:
      bbl-state: garden-windows-environments
      bbl-config: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: sriracha-lock-pool
        params:
          release: sriracha-lock-pool

- name: bbl-down-hummus
  serial: true
  serial_groups: [down]
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
      resource: sophiewigmore-cdct
    - get: hummus-lock-pool
    - get: garden-windows-environments
  - put: hummus-lock-pool
    timeout: 1m
    params:
      acquire: true
  - task: bosh-delete-all-deployments
    file: cf-deployment-concourse-tasks/bosh-delete-all-deployments/task.yml
    params:
      BBL_STATE_DIR: hummus
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: hummus-lock-pool
      params:
        release: hummus-lock-pool
  - task: bbl-down
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_STATE_DIR: hummus
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: hummus-lock-pool
        params:
          release: hummus-lock-pool

- name: bbl-down-tzatziki
  serial: true
  serial_groups: [down]
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
      resource: sophiewigmore-cdct
    - get: tzatziki-lock-pool
    - get: garden-windows-environments
  - put: tzatziki-lock-pool
    timeout: 1m
    params:
      acquire: true
  - task: bosh-delete-all-deployments
    file: cf-deployment-concourse-tasks/bosh-delete-all-deployments/task.yml
    params:
      BBL_STATE_DIR: tzatziki
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: tzatziki-lock-pool
      params:
        release: tzatziki-lock-pool
  - task: bbl-down
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_STATE_DIR: tzatziki
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: tzatziki-lock-pool
        params:
          release: tzatziki-lock-pool

- name: bbl-down-aioli
  serial: true
  serial_groups: [down]
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
      resource: sophiewigmore-cdct
    - get: aioli-lock-pool
    - get: garden-windows-environments
  - put: aioli-lock-pool
    timeout: 1m
    params:
      acquire: true
  - task: bosh-delete-all-deployments
    file: cf-deployment-concourse-tasks/bosh-delete-all-deployments/task.yml
    params:
      BBL_STATE_DIR: aioli
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: aioli-lock-pool
      params:
        release: aioli-lock-pool
  - task: bbl-down
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_STATE_DIR: aioli
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: aioli-lock-pool
        params:
          release: aioli-lock-pool


- name: bbl-down-pesto
  serial: true
  serial_groups: [down]
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
      resource: sophiewigmore-cdct
    - get: pesto-lock-pool
    - get: garden-windows-environments
  - put: pesto-lock-pool
    timeout: 1m
    params:
      acquire: true
  - task: bosh-delete-all-deployments
    file: cf-deployment-concourse-tasks/bosh-delete-all-deployments/task.yml
    params:
      BBL_STATE_DIR: pesto
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: pesto-lock-pool
      params:
        release: pesto-lock-pool
  - task: bbl-down
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_AZURE_CLIENT_ID:
      BBL_AZURE_CLIENT_SECRET:
      BBL_AZURE_TENANT_ID:
      BBL_AZURE_SUBSCRIPTION_ID:
      BBL_STATE_DIR: pesto
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: pesto-lock-pool
        params:
          release: pesto-lock-pool

- name: bbl-down-sriracha
  serial: true
  serial_groups: [down]
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
      resource: sophiewigmore-cdct
    - get: sriracha-lock-pool
    - get: garden-windows-environments
  - put: sriracha-lock-pool
    timeout: 1m
    params:
      acquire: true
  - task: bosh-delete-all-deployments
    file: cf-deployment-concourse-tasks/bosh-delete-all-deployments/task.yml
    params:
      BBL_STATE_DIR: sriracha
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: sriracha-lock-pool
      params:
        release: sriracha-lock-pool
  - task: bbl-down
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_AZURE_CLIENT_ID:
      BBL_AZURE_CLIENT_SECRET:
      BBL_AZURE_TENANT_ID:
      BBL_AZURE_SUBSCRIPTION_ID:
      BBL_STATE_DIR: sriracha
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: sriracha-lock-pool
        params:
          release: sriracha-lock-pool

- name: bbl-down-guac
  serial: true
  serial_groups: [down]
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
      resource: sophiewigmore-cdct
    - get: guac-lock-pool
    - get: garden-windows-environments
  - put: guac-lock-pool
    timeout: 1m
    params:
      acquire: true
  - task: bosh-delete-all-deployments
    file: cf-deployment-concourse-tasks/bosh-delete-all-deployments/task.yml
    params:
      BBL_STATE_DIR: guac
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: guac-lock-pool
      params:
        release: guac-lock-pool
  - task: bbl-down
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_AWS_ACCESS_KEY_ID: {{GUAC_AWS_ACCESS_KEY_ID}}
      BBL_AWS_SECRET_ACCESS_KEY: {{GUAC_AWS_SECRET_ACCESS_KEY}}
      BBL_STATE_DIR: guac
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: guac-lock-pool
        params:
          release: guac-lock-pool


# Task 2:
# Resource: bbl
# git clone bbl and do latest_version=`git describe --tags $(git rev-list --tags --max-count=1)`
# Download bbl from github.com/cloudfoundry/bosh-bootloader/releases/download/$latest_version/bbl-${latest_version}_linux_x86-64
# Spit out the executable's path as output_mapping: bbl_executable
# Task 3: (Run the generic bbldestory+bblup task)
# Task args: env-name, $BBL_GCP_SERVICE_ACCOUNT_KEY (passed as GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON and -l on the fly alias), $BBL_GCP_REGION
# If claimed, skip the task and go to the next environment
# i.e. if claimed, set task to exit 0 and set job to success, then move to the next job.
# If unclaimed, claim it (claimer stuff)
# Pull down the relevant gcs bucket
# use bbl received from input_mapping: bbl_executable
# bbl destroy
# (Change bbl_up_gcp to handle all iaas) call the bbl_up
# If failure at any stage, Exit the pipeline and be RED
# Repeat for all unclaimed environments
# First get the pipeline running for all gcp based environments, then think about guac later.
