groups:
- name: bbl-up
  jobs:
  - bbl-update-hummus
  - bbl-update-aioli
  - bbl-update-pesto
  - bbl-update-sriracha
  - bbl-update-alfredo
- name: deploy-cf
  jobs:
  - deploy-cf-hummus
- name: bbl-down
  jobs:
  - bbl-down-hummus
  - bbl-down-aioli
  - bbl-down-pesto
  - bbl-down-sriracha
  - bbl-down-alfredo

resources:
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: cf-deployment
  type: git
  source:
    branch: v11.2.0
    uri: https://github.com/cloudfoundry/cf-deployment.git

- name: hummus-lock-pool
  type: pool
  source:
    branch: master
    pool: hummus
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

- name: aioli-lock-pool
  type: pool
  source:
    branch: master
    pool: aioli
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

- name: pesto-lock-pool
  type: pool
  source:
    branch: master
    pool: pesto
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

- name: sriracha-lock-pool
  type: pool
  source:
    branch: master
    pool: sriracha
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

- name: alfredo-lock-pool
  type: pool
  source:
    branch: master
    pool: alfredo
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

- name: garden-windows-environments
  type: git
  source:
    branch: master
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:pivotal/garden-windows-environments

- name: garden-windows-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/garden-windows-ci

- name: sunday-morning
  type: time
  source:
    days: [Sunday]
    start: 12:00 AM
    stop: 1:00 AM

jobs:
- name: bbl-update-hummus
  serial: true
  serial_groups: [update]
  plan:
  - put: hummus-lock-pool
    params:
      acquire: true
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
    - get: sunday-morning
      trigger: true
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_GCP_REGION: us-east1
      BBL_STATE_DIR: hummus
      BBL_LB_CERT: cert.pem
      BBL_LB_KEY: key.pem
      LB_DOMAIN: hummus.cf-app.com
      BBL_ENV_NAME: hummus
    input_mapping:
      bbl-state: garden-windows-environments
      bbl-config: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: hummus-lock-pool
        params:
          release: hummus-lock-pool

- name: bbl-update-aioli
  serial: true
  serial_groups: [update]
  plan:
  - put: aioli-lock-pool
    params:
      acquire: true
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
    - get: sunday-morning
      trigger: true
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_GCP_REGION: us-east1
      BBL_STATE_DIR: aioli
      BBL_LB_CERT: cert.pem
      BBL_LB_KEY: key.pem
      LB_DOMAIN: aioli.cf-app.com
      BBL_ENV_NAME: aioli
    input_mapping:
      bbl-state: garden-windows-environments
      bbl-config: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: aioli-lock-pool
        params:
          release: aioli-lock-pool

- name: bbl-update-pesto
  serial: true
  serial_groups: [update]
  plan:
  - put: pesto-lock-pool
    params:
      acquire: true
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
    - get: sunday-morning
      trigger: true
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_GCP_REGION: us-east1
      BBL_STATE_DIR: pesto
      BBL_LB_CERT: cert.pem
      BBL_LB_KEY: key.pem
      LB_DOMAIN: pesto.cf-app.com
      BBL_ENV_NAME: pesto
    input_mapping:
      bbl-state: garden-windows-environments
      bbl-config: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: pesto-lock-pool
        params:
          release: pesto-lock-pool

- name: bbl-update-sriracha
  serial: true
  serial_groups: [update]
  plan:
  - put: sriracha-lock-pool
    params:
      acquire: true
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
    - get: sunday-morning
      trigger: true
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_GCP_REGION: us-central1
      BBL_STATE_DIR: sriracha
      BBL_LB_CERT: certs/cert.pem
      BBL_LB_KEY: certs/key.pem
      LB_DOMAIN: sriracha.cf-app.com
      BBL_ENV_NAME: sriracha
    input_mapping:
      bbl-state: garden-windows-environments
      bbl-config: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: sriracha-lock-pool
        params:
          release: sriracha-lock-pool

- name: bbl-update-alfredo
  serial: true
  serial_groups: [update]
  plan:
  - put: alfredo-lock-pool
    params:
      acquire: true
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
    - get: sunday-morning
      trigger: true
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_GCP_REGION: us-east1
      BBL_STATE_DIR: alfredo
      BBL_LB_CERT: cert.pem
      BBL_LB_KEY: key.pem
      LB_DOMAIN: alfredo.cf-app.com
      BBL_ENV_NAME: alfredo
    input_mapping:
      bbl-state: garden-windows-environments
      bbl-config: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: alfredo-lock-pool
        params:
          release: alfredo-lock-pool

- name: bbl-down-hummus
  serial: true
  serial_groups: [down]
  plan:
  - put: hummus-lock-pool
    params:
      acquire: true
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
  - task: bosh-delete-all-deployments
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    params:
      BBL_STATE_DIR: hummus
      DELETE_ALL_DEPLOYMENTS: true
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: hummus-lock-pool
      params:
        release: hummus-lock-pool
  - task: bbl-down
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_STATE_DIR: hummus
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: hummus-lock-pool
        params:
          release: hummus-lock-pool

- name: bbl-down-aioli
  serial: true
  serial_groups: [down]
  plan:
  - put: aioli-lock-pool
    params:
      acquire: true
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
  - task: bosh-delete-all-deployments
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    params:
      BBL_STATE_DIR: aioli
      DELETE_ALL_DEPLOYMENTS: true
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: aioli-lock-pool
      params:
        release: aioli-lock-pool
  - task: bbl-down
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_STATE_DIR: aioli
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: aioli-lock-pool
        params:
          release: aioli-lock-pool

- name: bbl-down-pesto
  serial: true
  serial_groups: [down]
  plan:
  - put: pesto-lock-pool
    params:
      acquire: true
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
  - task: bosh-delete-all-deployments
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    params:
      BBL_STATE_DIR: pesto
      DELETE_ALL_DEPLOYMENTS: true
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: pesto-lock-pool
      params:
        release: pesto-lock-pool
  - task: bbl-down
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_STATE_DIR: pesto
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: pesto-lock-pool
        params:
          release: pesto-lock-pool

- name: bbl-down-sriracha
  serial: true
  serial_groups: [down]
  plan:
  - put: sriracha-lock-pool
    params:
      acquire: true
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
  - task: bosh-delete-all-deployments
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    params:
      BBL_STATE_DIR: sriracha
      DELETE_ALL_DEPLOYMENTS: true
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: sriracha-lock-pool
      params:
        release: sriracha-lock-pool
  - task: bbl-down
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_STATE_DIR: sriracha
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: sriracha-lock-pool
        params:
          release: sriracha-lock-pool

- name: bbl-down-alfredo
  serial: true
  serial_groups: [down]
  plan:
  - put: alfredo-lock-pool
    params:
      acquire: true
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: garden-windows-environments
  - task: bosh-delete-all-deployments
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    params:
      BBL_STATE_DIR: alfredo
      DELETE_ALL_DEPLOYMENTS: true
    input_mapping:
      bbl-state: garden-windows-environments
    on_failure:
      put: alfredo-lock-pool
      params:
        release: alfredo-lock-pool
  - task: bbl-down
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_STATE_DIR: alfredo
    input_mapping:
      bbl-state: garden-windows-environments
    ensure:
      do:
      - put: garden-windows-environments
        params:
          repository: updated-bbl-state
          rebase: true
      - put: alfredo-lock-pool
        params:
          release: alfredo-lock-pool

- name: deploy-cf-hummus
  serial: true
  plan:
  - put: hummus-lock-pool
    params:
      acquire: true
  - in_parallel:
    - get: cf-deployment-concourse-tasks
    - get: cf-deployment
      trigger: true
    - get: garden-windows-ci
    - get: garden-windows-environments
  - task: collect-garden-windows-ci-ops-files
    file: cf-deployment-concourse-tasks/collect-ops-files/task.yml
    params:
      BASE_OPS_FILE_DIR: hummus
      NEW_OPS_FILES: |
        operations/latest-garden-runc.yml
        operations/latest-winc.yml
        operations/enable-rdp-2019.yml
        operations/windows2019-debug.yml
        operations/decrease-rep-evacuation-timeout.yml
        operations/install-windows-tools.yml
    input_mapping:
      base-ops-files: garden-windows-environments
      new-ops-files: garden-windows-ci
  - task: collect-cf-deployment-ops-files
    file: cf-deployment-concourse-tasks/collect-ops-files/task.yml
    params:
      BASE_OPS_FILE_DIR: hummus
      NEW_OPS_FILES: |
        operations/windows2019-cell.yml
        operations/use-online-windows2019fs.yml
        operations/use-latest-windows2019-stemcell.yml
        operations/use-latest-stemcell.yml
        operations/scale-to-one-az.yml
        operations/stop-skipping-tls-validation.yml
    input_mapping:
      base-ops-files: collected-ops-files
      new-ops-files: cf-deployment
  - task: deploy-cf
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    params:
      BBL_STATE_DIR: hummus
      SYSTEM_DOMAIN: hummus.cf-app.com
      OPS_FILES: |
        hummus/windows2019-cell.yml
        hummus/use-online-windows2019fs.yml
        hummus/use-latest-windows2019-stemcell.yml
        hummus/use-latest-stemcell.yml
        hummus/scale-to-one-az.yml
        hummus/stop-skipping-tls-validation.yml
        hummus/latest-garden-runc.yml
        hummus/latest-winc.yml
        hummus/enable-rdp-2019.yml
        hummus/decrease-rep-evacuation-timeout.yml
        hummus/windows2019-debug.yml
        hummus/install-windows-tools.yml
      VARS_FILES: hummus/cf/vars.yml
    input_mapping:
      bbl-state: garden-windows-environments
      ops-files: collected-ops-files
      vars-files: garden-windows-environments
    ensure:
      put: hummus-lock-pool
      params:
        release: hummus-lock-pool
