# Task 2:
# Resource: bbl
# git clone bbl and do latest_version=`git describe --tags $(git rev-list --tags --max-count=1)`
# Download bbl from github.com/cloudfoundry/bosh-bootloader/releases/download/$latest_version/bbl-${latest_version}_linux_x86-64
# Spit out the executable's path as output_mapping: bbl_executable
# Task 3: (Run the generic bbldestory+bblup task)
# Task args: env-name, $BBL_GCP_SERVICE_ACCOUNT_KEY (passed as GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON and -l on the fly alias), $BBL_GCP_REGION
# If claimed, skip the task and go to the next environment
# i.e. if claimed, set task to exit 0 and set job to success, then move to the next job.
# If unclaimed, claim it (claimer stuff)
# Pull down the relevant gcs bucket
# use bbl received from input_mapping: bbl_executable
# bbl destroy
# (Change bbl_up_gcp to handle all iaas) call the bbl_up
# If failure at any stage, Exit the pipeline and be RED
# Repeat for all unclaimed environments
# First get the pipeline running for all gcp based environments, then think about guac later.

resources:
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: hummus-lock-pool
  type: pool
  source:
    branch: master
    pool: hummus
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

- name: tzatziki-lock-pool
  type: pool
  source:
    branch: master
    pool: tzatziki
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:greenhouse-ci/locks

- name: garden-windows-environments
  type: git
  source:
    branch: master
    private_key: {{GREENHOUSE-CI_SSH_KEY}}
    uri: git@github.com:pivotal/garden-windows-environments

# - name: sunday-morning
#   type: time
#   source:
#     days: [Sunday]
#     start: 12:00 AM
#     stop: 1:00 AM

jobs:
# TODO: handle a lock already taken
# TODO: other environmnets
- name: bbl-update-hummus
  serial: true
  serial_groups: [update]
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: hummus-lock-pool
    - get: garden-windows-environments
    # - get: sunday-morning
    #   trigger: true
  - put: hummus-lock-pool
    timeout: 3h
    params:
      acquire: true
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_GCP_REGION: us-east1
      BBL_STATE_DIR: hummus
      BBL_LB_CERT: cert.pem
      BBL_LB_KEY: key.pem
      LB_DOMAIN: hummus.cf-app.com
      BBL_ENV_NAME: hummus
    input_mapping:
      bbl-state: garden-windows-environments
      bbl-config: garden-windows-environments
    ensure:
      put: garden-windows-environments
      params:
        repository: updated-bbl-state
        rebase: true
    on_success:
      put: hummus-lock-pool
      params:
        release: hummus-lock-pool

- name: bbl-update-tzatziki
  serial: true
  serial_groups: [update]
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: tzatziki-lock-pool
    - get: garden-windows-environments
    # - get: sunday-morning
    #   trigger: true
  - put: tzatziki-lock-pool
    timeout: 3h
    params:
      acquire: true
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{GARDEN_WINDOWS_DEV_SERVICE_ACCOUNT_JSON}}
      BBL_GCP_REGION: us-east1
      BBL_STATE_DIR: tzatziki
      BBL_LB_CERT: cert.pem
      BBL_LB_KEY: key.pem
      LB_DOMAIN: tzatziki.cf-app.com
      BBL_ENV_NAME: tzatziki
    input_mapping:
      bbl-state: garden-windows-environments
      bbl-config: garden-windows-environments
    ensure:
      put: garden-windows-environments
      params:
        repository: updated-bbl-state
        rebase: true
    on_success:
      put: tzatziki-lock-pool
      params:
        release: tzatziki-lock-pool
