resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:

# Git

- name: ci
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/garden-windows-ci.git

- name: tas-runtime
  type: git
  source:
    uri: git@github.com:pivotal/tas-runtime.git
    branch: main
    private_key: ((TAS-RUNTIME-GITHUB_PRIVATE_KEY))

- name: develop-branch
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/envoy-nginx-release.git
    private_key: ((TAS-RUNTIME-GITHUB_PRIVATE_KEY))

- name: develop-branch-full
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/envoy-nginx-release.git
    private_key: ((TAS-RUNTIME-GITHUB_PRIVATE_KEY))
    git_config:
    - name: user.email
      value: "pivotal-netgarden-eng@pivotal.io"
    - name: user.name
      value: "Greenhouse CI"

- name: develop-branch-mergeback
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/envoy-nginx-release.git
    private_key: ((TAS-RUNTIME-GITHUB_PRIVATE_KEY))

- name: release-branch
  type: git
  source:
    branch: release
    uri: git@github.com:cloudfoundry/envoy-nginx-release.git
    private_key: ((TAS-RUNTIME-GITHUB_PRIVATE_KEY))

- name: version
  type: semver
  source:
    access_key_id: ((BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY))
    bucket: envoy-nginx-release
    initial_version: 0.1.0
    key: version
    region_name: us-east-1

- name: github-release
  type: github-release
  source:
    user: cloudfoundry
    repository: envoy-nginx-release
    drafts: true
    access_token: ((tas-runtime-github-access-token))

- name: draft-github-release
  type: github-release
  source:
    user: cloudfoundry
    repository: envoy-nginx-release
    drafts: true
    access_token: ((tas-runtime-github-access-token))

- name: cf-acceptance-tests
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-acceptance-tests

- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: cf-deployment
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-deployment.git

- name: garden-windows-environments
  type: git
  source:
    branch: master
    private_key: ((TAS-RUNTIME-GITHUB_PRIVATE_KEY))
    uri: git@github.com:pivotal/garden-windows-environments

- name: golang-release-latest
  type: git
  icon: github-box
  source:
    uri: git@github.com:bosh-packages/golang-release.git
    private_key: ((TAS-RUNTIME-GITHUB_PRIVATE_KEY))
    branch: master
    tag_filter: v*

# S3

- name: gcp-windows-stemcell
  type: s3
  source:
    bucket: all-bosh-windows
    regexp: 2019/tested/gcp/light-bosh-stemcell-(.*)-google-kvm-windows2019-go_agent.tgz
    access_key_id: ((BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY))

# BOSH Deployment

- name: alfredo-cf-deployment
  type: bosh-deployment
  source:
    deployment: cf
    client: ((ALFREDO_BOSH_CLIENT))
    client_secret: ((ALFREDO_BOSH_CLIENT_SECRET))
    ca_cert: ((ALFREDO_BOSH_CA_CERT))
    target: ((ALFREDO_BOSH_ENVIRONMENT))
    jumpbox_url: ((ALFREDO_JUMPBOX_IP)):22
    jumpbox_ssh_key: ((ALFREDO_JUMPBOX_SSH_KEY))
    skip_check: true

jobs:
- name: bump-golang
  plan:
  - in_parallel:
    - get: tas-runtime
    - get: develop-branch-full
    - get: golang-release-latest
      trigger: true
  - task: bump-golang
    file: tas-runtime/ci/tasks/shared/upgrade-package-in-release/task.yml
    params:
      PACKAGE: golang-1.20-windows
      AWS_ACCESS_KEY_ID: ((BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID))
      AWS_SECRET_ACCESS_KEY: ((BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY))
      RELEASE: release
    input_mapping:
      release: develop-branch-full
      package-release: golang-release-latest
  - task: save-golang-version-to-file
    file: tas-runtime/ci/tasks/shared/save-golang-version-to-file/task.yml
    params:
      BRANCH: develop
      PACKAGE: golang-1.20-windows
    input_mapping:
      release: modified-release
  - put: develop-branch-full
    params:
      repository: modified-release

- name: test-envoy-nginx
  plan:
  - in_parallel:
    - get: ci
    - get: develop-branch
      trigger: true
  - task: run-ginkgo-exe
    tags: ["2019"]
    file: ci/tasks/ginkgo-test-windows/task.yml
    input_mapping:
      repo: develop-branch
    params:
      EPHEMERAL_DISK_TEMP_PATH: "C:\\var\\vcap\\data\\tmp"
      TEST_PATH: "repo/src/code.cloudfoundry.org/envoy-nginx"

- name: alfredo-cats
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: cf-deployment
      - get: develop-branch
        passed: [test-envoy-nginx]
        trigger: true
      - get: gcp-windows-stemcell
      - get: cf-acceptance-tests
      - get: cf-deployment-concourse-tasks
      - get: ci
      - get: garden-windows-environments
    - task: create-release
      file: ci/tasks/bosh-cr/task.yml
      input_mapping: { release: develop-branch }
    - task: get-linux-stemcell
      file: ci/tasks/get-gcp-linux-stemcell/task.yml
      output_mapping: { stemcell: gcp-linux-stemcell }
    - task: delete-deployment
      file: ci/tasks/bosh-deld/task.yml
      params:
        BOSH_DEPLOYMENT: cf
        BOSH_ENVIRONMENT: {{ALFREDO_BOSH_ENVIRONMENT}}
        BOSH_CLIENT: {{ALFREDO_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{ALFREDO_BOSH_CLIENT_SECRET}}
        BOSH_CA_CERT: {{ALFREDO_BOSH_CA_CERT}}
        JUMPBOX_IP: {{ALFREDO_JUMPBOX_IP}}
        JUMPBOX_SSH_KEY: {{ALFREDO_JUMPBOX_SSH_KEY}}
    - task: delete-stemcells
      file: ci/tasks/bosh-delete-stemcells/task.yml
      params:
        BOSH_CLIENT: {{ALFREDO_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{ALFREDO_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{ALFREDO_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{ALFREDO_BOSH_CA_CERT}}
        JUMPBOX_IP: {{ALFREDO_JUMPBOX_IP}}
        JUMPBOX_SSH_KEY: {{ALFREDO_JUMPBOX_SSH_KEY}}
    - put: alfredo-cf-deployment
      params:
        manifest: cf-deployment/cf-deployment.yml
        stemcells:
        - gcp-linux-stemcell/*.tgz
        - gcp-windows-stemcell/*.tgz
        releases:
        - release-tarball/*.tgz
        ops_files:
        - cf-deployment/operations/scale-to-one-az.yml
        - cf-deployment/operations/windows2019-cell.yml
        - cf-deployment/operations/use-online-windows2019fs.yml
        - cf-deployment/operations/use-latest-windows2019-stemcell.yml
        - ci/operations/scale-down-windows2019.yml
        - ci/operations/enable-nginx-routing-integrity-windows2019.yml
        - ci/operations/decrease-rep-evacuation-timeout.yml
        - ci/operations/use-2-azs-for-router.yml
        vars_files:
        - garden-windows-environments/alfredo/cf/vars.yml
        cleanup: true
      get_params:
        skip_export: true
    - task: clean-up
      file: ci/tasks/bosh-cleanup/task.yml
      params:
        BOSH_CLIENT: {{ALFREDO_BOSH_CLIENT}}
        BOSH_CLIENT_SECRET: {{ALFREDO_BOSH_CLIENT_SECRET}}
        BOSH_ENVIRONMENT: {{ALFREDO_BOSH_ENVIRONMENT}}
        BOSH_CA_CERT: {{ALFREDO_BOSH_CA_CERT}}
        JUMPBOX_IP: {{ALFREDO_JUMPBOX_IP}}
        JUMPBOX_SSH_KEY: {{ALFREDO_JUMPBOX_SSH_KEY}}
    - task: generate-integration-config
      file: ci/tasks/generate-integration-config/task.yml
      params:
        ADMIN_PASSWORD: {{ALFREDO_ADMIN_PASSWORD}}
        ADMIN_USER: admin
        API: api.alfredo.cf-app.com
        APPS_DOMAIN: alfredo.cf-app.com
        UNALLOCATED_IP: 10.0.0.5
        WINDOWS_STACK: windows
    - task: cats
      file: cf-deployment-concourse-tasks/run-cats/task.yml
      params:
        NODES: 4
      attempts: 3
      on_success:
        task: delete-deployment
        file: ci/tasks/bosh-deld/task.yml
        params:
          BOSH_DEPLOYMENT: cf
          BOSH_ENVIRONMENT: {{ALFREDO_BOSH_ENVIRONMENT}}
          BOSH_CLIENT: {{ALFREDO_BOSH_CLIENT}}
          BOSH_CLIENT_SECRET: {{ALFREDO_BOSH_CLIENT_SECRET}}
          BOSH_CA_CERT: {{ALFREDO_BOSH_CA_CERT}}
          JUMPBOX_IP: {{ALFREDO_JUMPBOX_IP}}
          JUMPBOX_SSH_KEY: {{ALFREDO_JUMPBOX_SSH_KEY}}

- name: ship-what
  plan:
    - in_parallel:
        steps:
        - get: tas-runtime
        - get: develop-branch
          passed:
            - alfredo-cats
          trigger: true
        - get: release-branch
          params:
            submodules: none
        - get: github-release
        - get: version
    - task: check-safe-to-push-to-release-branch
      file: tas-runtime/ci/tasks/shared/checkit/task.yml
      input_mapping:
        dev-repo: develop-branch
        release-repo: release-branch
    - task: print-bosh-job-spec-diff
      file: tas-runtime/ci/tasks/shared/print-bosh-job-spec-diff/task.yml
      input_mapping:
        release: develop-branch
      params:
        PRE_RELEASE: "true"
    - task: build-release-notes
      file: tas-runtime/ci/tasks/shared/build-release-notes/task.yml
      input_mapping:
        release: develop-branch
        previous-github-release: github-release
        bosh-job-diff: bosh-job-diff
      params:
        RELEASE_NAME: envoy-nginx-release
      output_mapping:
        release-notes: gr-notes

- name: shipit
  serial: true
  plan:
    - in_parallel:
        steps:
        - get: tas-runtime
        - get: develop-branch
          passed: 
            - ship-what
        - get: release-branch
          params:
            submodules: none
        - get: github-release
        - get: version
        - get: develop-branch-mergeback
          params:
            submodules: none
    - task: check-safe-to-push-to-release-branch
      file: tas-runtime/ci/tasks/shared/checkit/task.yml
      input_mapping:
        dev-repo: develop-branch
        release-repo: release-branch
    - task: print-bosh-job-spec-diff 
      file: tas-runtime/ci/tasks/shared/print-bosh-job-spec-diff/task.yml
      input_mapping:
        release: develop-branch
      params:
        PRE_RELEAE: true
    - task: build-release-notes
      file: tas-runtime/ci/tasks/shared/build-release-notes/task.yml
      input_mapping:
        release: develop-branch
        previous-github-release: github-release
        bosh-job-diff: bosh-job-diff
      params:
        RELEASE_NAME: envoy-nginx-release
      output_mapping:
        release-notes: envoy-nginx-notes
    - task: create-final-release
      file: tas-runtime/ci/tasks/shared/create-final-release/task.yml
      input_mapping:
        release: develop-branch
      params:
        aws_access_key_id: ((bosh_windows_s3_admin_access_key_id))
        aws_secret_access_key: ((bosh_windows_s3_admin_secret_access_key))
        release_name: envoy-nginx
    - put: release-branch
      params:
        repository: release-repo
        tag: version/number
        tag_prefix: v
    - task: merge-release-into-develop
      file: tas-runtime/ci/tasks/shared/merge-release/task.yml
      params:
        release_branch: release
      input_mapping:
        release: release-branch
        dev: develop-branch-mergeback
    - in_parallel:
        steps:
        - put: draft-github-release
          params:
            name: version/number
            tag: version/number
            tag_prefix: v
            body: envoy-nginx-notes/notes.md
            globs:
            - final-release/envoy-nginx-*.tgz
        - put: develop-branch-mergeback
          params:
            repository: release-merged
    - get: next-version
      resource: version
      params: {bump: minor}
    - put: next-version
      resource: version
      params: {file: next-version/number}
