resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/garden-windows-ci.git

- name: envoy
  type: git
  source:
    branch: windows-linux-build
    uri: https://github.com/greenhouse-org/envoy.git

- name: envoy-windows-bucket
  type: s3
  source:
    bucket: garden-windows-envoy
    regexp: envoy-(.*)-.*.exe
    access_key_id: {{BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY}}

jobs:
- name: envoy-windows-debug
  serial: true
  serial_groups: [envoy]
  public: true
  plan:
  - get: ci
  - get: envoy
    trigger: true
  - task: envoy-ci-windows
    tags: [envoy]
    file: ci/tasks/envoy-ci-windows/task.yml
    params:
      BUILD_TYPE: debug

- name: envoy-windows-release
  serial: true
  serial_groups: [envoy]
  public: true
  plan:
  - get: ci
  - get: envoy
    trigger: true
  - task: envoy-ci-windows
    tags: [envoy]
    file: ci/tasks/envoy-ci-windows/task.yml
    params:
      BUILD_TYPE: release
  - put: envoy-windows-bucket
    params:
      file: envoy-exe/envoy-*-*.exe
