resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/garden-windows-ci.git
- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests
- name: cf-deployment
  type: git
  source:
    branch: release-candidate
    uri: https://github.com/cloudfoundry/cf-deployment.git
- name: winc-release-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry-incubator/winc-release.git
- name: windows2016fs-release-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry-incubator/windows2016fs-online-release.git
- name: garden-windows-bosh-release-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry-incubator/garden-windows-bosh-release.git
- name: bosh-dns-release-master
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-dns-release.git
- name: vsphere-windows2012R2-stemcell
  type: s3
  source:
   bucket: all-bosh-windows
   regexp: 2012R2/tested/vsphere/internal/bosh-stemcell-(.*)-vsphere-esxi-windows2012R2-go_agent.tgz
   access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
   secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
- name: vsphere-windows1709-stemcell
  type: s3
  source:
   bucket: all-bosh-windows
   regexp: 1709/tested/vsphere/internal/bosh-stemcell-(.*)-vsphere-esxi-windows2016-go_agent.tgz
   access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
   secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
- name: mulgore-cf-deployment
  type: bosh-deployment
  source:
    deployment: cf
    client: {{MULGORE_BOSH_CLIENT}}
    client_secret: {{MULGORE_BOSH_CLIENT_SECRET}}
    ca_cert: {{MULGORE_BOSH_CA_CERT}}
    target: {{MULGORE_BOSH_ENVIRONMENT}}
    jumpbox_url: {{MULGORE_JUMPBOX_URL}}
    jumpbox_ssh_key: {{MULGORE_JUMPBOX_SSH_KEY}}
    vars_store:
      provider: gcs
      config:
        bucket: mulgore
        file_name: cf/creds.yml
        json_key: {{SPITFIRE_SERVICE_ACCOUNT_JSON}}
- name: cfbench
  type: git
  source:
    uri: https://github.com/teddyking/cfbench.git
- name: every-5mins
  type: time
  source:
    interval: 5m
- name: every-1min
  type: time
  source:
    interval: 1m

jobs:
- name: mulgore-deploy-cf
  serial: true
  serial_groups:
  - cfbench
  - longrunning-windows2016
  - longrunning-windows2012R2
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: cf-deployment
      trigger: true
      tags: [vsphere]
    - get: vsphere-windows2012R2-stemcell
      tags: [vsphere]
    - get: vsphere-windows1709-stemcell
      tags: [vsphere]
    - get: winc-release-develop
      trigger: true
      tags: [vsphere]
    - get: windows2016fs-release-develop
      trigger: true
      tags: [vsphere]
    - get: garden-windows-bosh-release-develop
      trigger: true
      tags: [vsphere]
    - get: bosh-dns-release-master
      trigger: true
      tags: [vsphere]
  - aggregate:
    - task: get-linux-stemcell
      file: ci/tasks/get-vsphere-linux-stemcell/task.yml
      output_mapping: { stemcell: vsphere-linux-stemcell }
      tags: [vsphere]
    - task: get-cf-vars
      file: ci/tasks/get-gcs-file/task.yml
      output_mapping: { output: cf-vars }
      params:
        BUCKET: mulgore
        FILE_NAME: cf/vars.yml
        SERVICE_ACCOUNT_KEY: {{SPITFIRE_SERVICE_ACCOUNT_JSON}}
      tags: [vsphere]
    - task: create-winc-release
      file: ci/tasks/bosh-cr/task.yml
      input_mapping:
        release: winc-release-develop
      output_mapping:
        release-tarball: winc-tarball
      tags: [vsphere]
    - task: create-windows2016fs-release
      file: ci/tasks/bosh-cr/task.yml
      input_mapping:
        release: windows2016fs-release-develop
      output_mapping:
        release-tarball: windows2016fs-tarball
      tags: [vsphere]
    - task: create-garden-windows-bosh-release
      file: ci/tasks/bosh-cr/task.yml
      input_mapping:
        release: garden-windows-bosh-release-develop
      output_mapping:
        release-tarball: garden-windows-tarball
      tags: [vsphere]
    - task: create-bosh-dns-release
      file: ci/tasks/bosh-cr/task.yml
      input_mapping:
        release: bosh-dns-release-master
      output_mapping:
        release-tarball: bosh-dns-tarball
      tags: [vsphere]
  - put: mulgore-cf-deployment
    params:
      manifest: cf-deployment/cf-deployment.yml
      stemcells:
      - vsphere-linux-stemcell/*.tgz
      - vsphere-windows2012R2-stemcell/*.tgz
      - vsphere-windows1709-stemcell/*.tgz
      releases:
      - winc-tarball/*.tgz
      - windows2016fs-tarball/*.tgz
      - garden-windows-tarball/*.tgz
      - bosh-dns-tarball/*.tgz
      ops_files:
      - cf-deployment/operations/scale-to-one-az.yml
      - cf-deployment/operations/windows-cell.yml
      - cf-deployment/operations/windows2016-cell.yml
      - cf-deployment/operations/use-latest-windows-stemcell.yml
      - cf-deployment/operations/use-latest-windows2016-stemcell.yml
      - cf-deployment/operations/experimental/enable-prefer-declarative-healthchecks.yml
      - cf-deployment/operations/experimental/enable-prefer-declarative-healthchecks-windows.yml
      - cf-deployment/operations/experimental/enable-prefer-declarative-healthchecks-windows2016.yml
      - cf-deployment/operations/experimental/use-bosh-dns.yml
      # - cf-deployment/operations/experimental/use-bosh-dns-for-containers.yml
      # - cf-deployment/operations/experimental/use-bosh-dns-for-windows2016-containers.yml
      # - cf-deployment/operations/experimental/disable-consul.yml
      # - cf-deployment/operations/experimental/disable-consul-windows.yml
      # - cf-deployment/operations/experimental/skip-consul-cell-registrations.yml
      # - cf-deployment/operations/experimental/skip-consul-locks.yml
      - cf-deployment/operations/experimental/enable-instance-identity-credentials.yml
      - cf-deployment/operations/experimental/enable-instance-identity-credentials-windows.yml
      - cf-deployment/operations/experimental/enable-instance-identity-credentials-windows2016.yml
      - ci/operations/windows2016-prs.yml
      - ci/operations/windows2016-debug.yml
      - ci/operations/latest-winc.yml
      - ci/operations/latest-windows2016fs-release.yml
      - ci/operations/latest-garden-windows.yml
      - ci/operations/latest-bosh-dns.yml
      vars_files:
      - cf-vars/vars.yml
      cleanup: true
    get_params:
      skip_export: true
    tags: [vsphere]
  - task: create-longrunning-spaces
    file: ci/tasks/create-longrunning-spaces/task.yml
    params:
      CF_API: api.mulgore.cf-app.com
      CF_USERNAME: admin
      CF_PASSWORD: {{MULGORE_ADMIN_PASSWORD}}
    tags: [vsphere]

- name: mulgore-cfbench-windows2016
  serial: true
  serial_groups:
  - cfbench
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: cfbench
      tags: [vsphere]
    - get: cf-acceptance-tests
      tags: [vsphere]
    - get: every-5mins
      trigger: true
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-deploy-cf]
      tags: [vsphere]
  - task: cfbench
    file: ci/tasks/cfbench/task.yml
    input_mapping: {app: cf-acceptance-tests}
    params:
      CF_API: api.mulgore.cf-app.com
      CF_STACK: windows2016
      CF_USERNAME: admin
      CF_PASSWORD: {{MULGORE_ADMIN_PASSWORD}}
      CF_ORG: cfbench
      CF_SPACE: windows2016
      APP_DIR: app/assets/nora/NoraPublished
      APP_BUILDPACK: hwc_buildpack
      DATADOG_API_KEY: {{DATADOG_API_KEY}}
      DATADOG_APPLICATION_KEY: {{DATADOG_APPLICATION_KEY}}
    tags: [vsphere]

- name: mulgore-push-longrunning-app-windows2016
  serial: true
  serial_groups:
  - longrunning-windows2016
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: cf-acceptance-tests
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-deploy-cf]
      tags: [vsphere]
  - task: push-app
    file: ci/tasks/push-app/task.yml
    input_mapping: {app: cf-acceptance-tests}
    params:
      CF_API: api.mulgore.cf-app.com
      CF_STACK: windows2016
      CF_USERNAME: admin
      CF_PASSWORD: {{MULGORE_ADMIN_PASSWORD}}
      CF_ORG: longrunning
      CF_SPACE: windows2016
      APP_DIR: app/assets/nora/NoraPublished
      APP_BUILDPACK: hwc_buildpack
    tags: [vsphere]

- name: mulgore-curl-longrunning-app-windows2016
  serial: true
  serial_groups:
  - longrunning-windows2016
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: every-1min
      trigger: true
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-push-longrunning-app-windows2016]
      tags: [vsphere]
  - task: curl-app
    file: ci/tasks/curl-app/task.yml
    params:
      CF_APP_URL: longrunning-windows2016.mulgore.cf-app.com
      DATADOG_TAG: windows2016
      DATADOG_API_KEY: {{DATADOG_API_KEY}}
      DATADOG_APPLICATION_KEY: {{DATADOG_APPLICATION_KEY}}
    tags: [vsphere]

- name: mulgore-cfbench-windows2012R2
  serial: true
  serial_groups:
  - cfbench
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: cfbench
      tags: [vsphere]
    - get: cf-acceptance-tests
      tags: [vsphere]
    - get: every-5mins
      trigger: true
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-deploy-cf]
      tags: [vsphere]
  - task: cfbench
    file: ci/tasks/cfbench/task.yml
    input_mapping: {app: cf-acceptance-tests}
    params:
      CF_API: api.mulgore.cf-app.com
      CF_STACK: windows2012R2
      CF_USERNAME: admin
      CF_PASSWORD: {{MULGORE_ADMIN_PASSWORD}}
      CF_ORG: cfbench
      CF_SPACE: windows2012R2
      APP_DIR: app/assets/nora/NoraPublished
      APP_BUILDPACK: hwc_buildpack
      DATADOG_API_KEY: {{DATADOG_API_KEY}}
      DATADOG_APPLICATION_KEY: {{DATADOG_APPLICATION_KEY}}
    tags: [vsphere]

- name: mulgore-push-longrunning-app-windows2012R2
  serial: true
  serial_groups:
  - longrunning-windows2012R2
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: cf-acceptance-tests
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-deploy-cf]
      tags: [vsphere]
  - task: push-app
    file: ci/tasks/push-app/task.yml
    input_mapping: {app: cf-acceptance-tests}
    params:
      CF_API: api.mulgore.cf-app.com
      CF_STACK: windows2012R2
      CF_USERNAME: admin
      CF_PASSWORD: {{MULGORE_ADMIN_PASSWORD}}
      CF_ORG: longrunning
      CF_SPACE: windows2012R2
      APP_DIR: app/assets/nora/NoraPublished
      APP_BUILDPACK: hwc_buildpack
    tags: [vsphere]

- name: mulgore-curl-longrunning-app-windows2012R2
  serial: true
  serial_groups:
  - longrunning-windows2012R2
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: every-1min
      trigger: true
      tags: [vsphere]
    - get: mulgore-cf-deployment
      trigger: true
      passed: [mulgore-push-longrunning-app-windows2012R2]
      tags: [vsphere]
  - task: curl-app
    file: ci/tasks/curl-app/task.yml
    params:
      CF_APP_URL: longrunning-windows2012R2.mulgore.cf-app.com
      DATADOG_TAG: windows2012R2
      DATADOG_API_KEY: {{DATADOG_API_KEY}}
      DATADOG_APPLICATION_KEY: {{DATADOG_APPLICATION_KEY}}
    tags: [vsphere]
