resources:

# Git

- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/garden-windows-ci.git

- name: windows2016fs-develop
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/windows2016fs.git
    private_key: ((CLOUDFOUNDRYINCUBATOR_WINDOWS2016FS_DEPLOY_KEY))

- name: windows2016fs-master
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/windows2016fs.git
    private_key: ((CLOUDFOUNDRYINCUBATOR_WINDOWS2016FS_DEPLOY_KEY))

- name: windowsfs-dockerfile-1709
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/windows2016fs.git
    paths: [ 1709/Dockerfile ]

- name: windowsfs-dockerfile-1803
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/windows2016fs.git
    paths: [ 1803/Dockerfile ]

- name: windowsfs-dockerfile-2019
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/windows2016fs.git
    paths: [ 2019/Dockerfile ]

# Docker Image

- name: windowsservercore-1709
  type: docker-image
  source:
    repository: mcr.microsoft.com/windows/servercore
    tag: "1709-amd64"

- name: windowsservercore-1803
  type: docker-image
  source:
    repository: mcr.microsoft.com/windows/servercore
    tag: "1803-amd64"

- name: windowsservercore-2019
  type: docker-image
  source:
    repository: mcr.microsoft.com/windows/servercore
    tag: "ltsc2019-amd64"

# GitHub Release

- name: git-setup
  type: github-release
  source:
    user: git-for-windows
    repository: git
    access_token: ((GREENHOUSE_CI_ACCESS_TOKEN))

# S3

- name: tar
  type: s3
  source:
    bucket: bosh-windows-dependencies
    regexp: tar-(.*).exe
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))

# Semver

- name: image-version-1709
  type: semver
  source:
    access_key_id: ((BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY))
    bucket: windows1709fs
    initial_version: 1709.0.1
    key: image-version
    region_name: us-east-1

- name: image-version-1803
  type: semver
  source:
    access_key_id: ((BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY))
    bucket: windows1803fs
    initial_version: 1803.0.1
    key: image-version
    region_name: us-east-1

- name: image-version-2019
  type: semver
  source:
    access_key_id: ((BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY))
    bucket: windows2019fs
    initial_version: 2019.0.1
    key: image-version
    region_name: us-east-1

jobs:
- name: build-and-push-1709
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: windows2016fs-develop
    - get: windowsservercore-1709
      trigger: true
      params:
        save: false
        rootfs: false
        skip_download: true
    - get: windowsfs-dockerfile-1709
      trigger: true
    - get: git-setup
      params:
        globs: [Git-*-64-bit.exe]
    - get: tar
    - get: image-version-1709
      params: {bump: patch}
  - task: build-and-push
    file: ci/tasks/docker-build-and-push/task.yml
    input_mapping:
      repo: windowsfs-dockerfile-1709
      version: image-version-1709
    params:
      EPHEMERAL_DISK_TEMP_PATH: "C:\\var\\vcap\\data\\tmp"
      DOCKERFILE: repo/1709/Dockerfile
      IMAGE_NAME: cloudfoundry/windows2016fs
      DOCKER_USERNAME: ((DOCKER_USERNAME))
      DOCKER_PASSWORD: ((DOCKER_PASSWORD))
      OS_VERSION: "1709"
  - task: update-image-tag
    file: ci/tasks/update-image-tag/task.yml
    input_mapping:
      windows2016fs: windows2016fs-develop
      image-version: image-version-1709
    params:
      OS_VERSION: "1709"
  - task: commit-changes
    file: ci/tasks/commit/task.yml
    input_mapping:
      repo: windows2016fs-updated
    output_mapping:
      repo_with_commit: windowsfs-commit
    params:
      MESSAGE: "Updated image tag"
  - put: windows2016fs-master
    params:
      repository: windowsfs-commit
      rebase: true
  - put: image-version-1709
    params: {file: image-version-1/version}

- name: build-and-push-1803
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: windows2016fs-develop
    - get: windowsservercore-1803
      trigger: true
      params:
        save: false
        rootfs: false
        skip_download: true
    - get: windowsfs-dockerfile-1803
      trigger: true
    - get: git-setup
      params:
        globs: [Git-*-64-bit.exe]
    - get: tar
    - get: image-version-1803
      params: {bump: patch}
  - task: build-and-push
    tags: [1803]
    file: ci/tasks/docker-build-and-push/task.yml
    input_mapping:
      repo: windowsfs-dockerfile-1803
      version: image-version-1803
    params:
      EPHEMERAL_DISK_TEMP_PATH: "C:\\var\\vcap\\data\\tmp"
      DOCKERFILE: repo/1803/Dockerfile
      IMAGE_NAME: cloudfoundry/windows2016fs
      DOCKER_USERNAME: ((DOCKER_USERNAME))
      DOCKER_PASSWORD: ((DOCKER_PASSWORD))
      OS_VERSION: "1803"
  - task: update-image-tag
    file: ci/tasks/update-image-tag/task.yml
    input_mapping:
      windows2016fs: windows2016fs-develop
      image-version: image-version-1803
    params:
      OS_VERSION: "1803"
  - task: commit-changes
    file: ci/tasks/commit/task.yml
    input_mapping:
      repo: windows2016fs-updated
    output_mapping:
      repo_with_commit: windowsfs-commit
    params:
      MESSAGE: "Updated image tag"
  - put: windows2016fs-master
    params:
      repository: windowsfs-commit
      rebase: true
  - put: image-version-1803
    params: {file: image-version-1803/version}

- name: build-and-push-2019
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: windows2016fs-develop
    - get: windowsservercore-2019
      trigger: true
      params:
        save: false
        rootfs: false
        skip_download: true
    - get: windowsfs-dockerfile-2019
      trigger: true
    - get: git-setup
      params:
        globs: [Git-*-64-bit.exe]
    - get: tar
    - get: image-version-2019
      params: {bump: patch}
  - task: build-and-push
    tags: [2019]
    file: ci/tasks/docker-build-and-push/task.yml
    input_mapping:
      repo: windowsfs-dockerfile-2019
      version: image-version-2019
    params:
      EPHEMERAL_DISK_TEMP_PATH: "C:\\var\\vcap\\data\\tmp"
      DOCKERFILE: repo/2019/Dockerfile
      IMAGE_NAME: cloudfoundry/windows2016fs
      DOCKER_USERNAME: ((DOCKER_USERNAME))
      DOCKER_PASSWORD: ((DOCKER_PASSWORD))
      OS_VERSION: "2019"
  - task: update-image-tag
    file: ci/tasks/update-image-tag/task.yml
    input_mapping:
      windows2016fs: windows2016fs-develop
      image-version: image-version-2019
    params:
      OS_VERSION: "2019"
  - task: commit-changes
    file: ci/tasks/commit/task.yml
    input_mapping:
      repo: windows2016fs-updated
    output_mapping:
      repo_with_commit: windowsfs-commit
    params:
      MESSAGE: "Updated image tag"
  - put: windows2016fs-master
    params:
      repository: windowsfs-commit
      rebase: true
  - put: image-version-2019
    params: {file: image-version-1/version}
