resource_types:
- name: command-runner
  type: docker-image
  source:
    repository: cloudfoundrydevelopers/command-runner-resource
    tag: latest

resources:
- name: vcredist-ucrt
  type: command-runner
  source:
    version_key: "url"
    check_command: "curl --location --silent --write-out %{url_effective} --request HEAD https://aka.ms/vs/16/release/vc_redist.x64.exe"
    in_command:    "curl --location --silent --fail --output $1/vcredist-ucrt.x64.exe https://aka.ms/vs/16/release/vc_redist.x64.exe"
- name: vcredist-2010
  type: command-runner
  source:
    version_key: "2010-hardcoded-url"
    check_command: "echo https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x64.exe"
    in_command:    "curl --silent --fail --output $1/vcredist-2010.x64.exe https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x64.exe"


# Git

- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/garden-windows-ci.git

- name: windows2016fs-master
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/windows2016fs.git
    private_key: ((CLOUDFOUNDRYINCUBATOR_WINDOWS2016FS_DEPLOY_KEY))

- name: windows2016fs-develop
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/windows2016fs.git
    private_key: ((CLOUDFOUNDRYINCUBATOR_WINDOWS2016FS_DEPLOY_KEY))

- name: windowsfs-dockerfile-1803
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/windows2016fs.git
    paths: [ 1803/Dockerfile ]

- name: windowsfs-dockerfile-2019
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/windows2016fs.git
    paths: [ 2019/Dockerfile ]

# Docker Image

- name: windowsservercore-1803
  type: docker-image
  source:
    repository: mcr.microsoft.com/windows/servercore
    tag: "1803-amd64"

- name: windowsservercore-2019
  type: docker-image
  source:
    repository: mcr.microsoft.com/windows/servercore
    tag: "1809-amd64"

# Git for Windows Release

- name: git-setup
  type: github-release
  source:
    user: git-for-windows
    repository: git
    access_token: ((GREENHOUSE_CI_ACCESS_TOKEN))

# S3

- name: tar
  type: s3
  source:
    bucket: bosh-windows-dependencies
    regexp: tar-(.*).exe
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))

# Semver

- name: image-version-1803
  type: semver
  source:
    access_key_id: ((BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY))
    bucket: windows1803fs
    initial_version: 1803.0.1
    key: image-version
    region_name: us-east-1

- name: image-version-2019
  type: semver
  source:
    access_key_id: ((BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY))
    bucket: windows2019fs
    initial_version: 2019.0.1
    key: image-version
    region_name: us-east-1

jobs:
- name: build-and-push-1803
  serial: true
  serial_groups: [build-and-push]
  plan:
  - in_parallel:
    - get: ci
    - get: windows2016fs-develop
    - get: windowsservercore-1803
      trigger: true
      params:
        save: false
        rootfs: false
        skip_download: true
    - get: windowsfs-dockerfile-1803
      trigger: true
    - get: git-setup
      params:
        globs: [Git-*-64-bit.exe]
    - get: tar
    - get: vcredist-ucrt
      trigger: true
    - get: vcredist-2010
      trigger: true
    - get: image-version-1803
      params: {bump: patch}
  - task: build-and-push
    tags: [1803]
    file: ci/tasks/docker-build-and-push/task.yml
    input_mapping:
      repo: windows2016fs-develop
      version: image-version-1803
    params:
      EPHEMERAL_DISK_TEMP_PATH: "C:\\var\\vcap\\data\\tmp"
      DOCKERFILE: repo/1803/Dockerfile
      IMAGE_NAME: cloudfoundry/windows2016fs
      DOCKER_USERNAME: ((DOCKER_USERNAME))
      DOCKER_PASSWORD: ((DOCKER_PASSWORD))
      OS_VERSION: "1803"
      SHARE_IP: ((SHARE_IP))
      SHARE_FQDN: ((SHARE_FQDN))
      SHARE_NAME: ((SHARE_NAME))
      SHARE_USERNAME: ((SHARE_USERNAME))
      SHARE_PASSWORD: ((SHARE_PASSWORD))
  - task: update-image-tag
    file: ci/tasks/update-image-tag/task.yml
    input_mapping:
      windows2016fs: windows2016fs-develop
      image-version: image-version-1803
    params:
      OS_VERSION: "1803"
  - task: commit-changes
    file: ci/tasks/commit/task.yml
    input_mapping:
      repo: windows2016fs-updated
    output_mapping:
      repo_with_commit: windowsfs-commit
    params:
      MESSAGE: "Updated 1803 image tag"
  - put: windows2016fs-master
    params:
      repository: windowsfs-commit
  - put: windows2016fs-develop
    params:
      repository: windowsfs-commit
      merge: true
  - put: image-version-1803
    params: {file: image-version-1803/version}

- name: build-and-push-2019
  serial: true
  serial_groups: [build-and-push]
  plan:
  - in_parallel:
    - get: ci
    - get: windows2016fs-develop
    - get: windowsservercore-2019
      trigger: true
      params:
        save: false
        rootfs: false
        skip_download: true
    - get: windowsfs-dockerfile-2019
      trigger: true
    - get: git-setup
      params:
        globs: [Git-*-64-bit.exe]
    - get: tar
    - get: vcredist-ucrt
      trigger: true
    - get: vcredist-2010
      trigger: true
    - get: image-version-2019
      params: {bump: patch}
  - task: build-and-push
    tags: [2019]
    file: ci/tasks/docker-build-and-push/task.yml
    input_mapping:
      repo: windows2016fs-develop
      version: image-version-2019
    params:
      EPHEMERAL_DISK_TEMP_PATH: "C:\\var\\vcap\\data\\tmp"
      DOCKERFILE: repo/2019/Dockerfile
      IMAGE_NAME: cloudfoundry/windows2016fs
      DOCKER_USERNAME: ((DOCKER_USERNAME))
      DOCKER_PASSWORD: ((DOCKER_PASSWORD))
      OS_VERSION: "2019"
  - task: update-image-tag
    file: ci/tasks/update-image-tag/task.yml
    input_mapping:
      windows2016fs: windows2016fs-develop
      image-version: image-version-2019
    params:
      OS_VERSION: "2019"
  - task: commit-changes
    file: ci/tasks/commit/task.yml
    input_mapping:
      repo: windows2016fs-updated
    output_mapping:
      repo_with_commit: windowsfs-commit
    params:
      MESSAGE: "Updated 2019 image tag"
  - put: windows2016fs-master
    params:
      repository: windowsfs-commit
  - put: windows2016fs-develop
    params:
      repository: windowsfs-commit
      merge: true
  - put: image-version-2019
    params: {file: image-version-2019/version}
