resources:
- name: s3-bucket
  type: s3
  source:
    bucket: bosh-windows-dependencies
    regexp: tar-(.*).exe
    access_key_id: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
    secret_access_key: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
- name: bsdtar
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/bsdtar.git
    private_key: {{CLOUDFOUNDRY_BSDTAR_DEPLOY_KEY}}
- name: libarchive
  type: git
  source:
    branch: master
    uri: https://github.com/libarchive/libarchive.git
    tag_filter: v*
- name: zlib
  type: git
  source:
    branch: master
    uri: https://github.com/madler/zlib.git
    tag_filter: v*
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/garden-windows-ci.git

resource_types: []

jobs:
- name: bump-submodules
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: bsdtar
    - get: libarchive
      trigger: true
    - get: zlib
      trigger: true
  - task: bump-libarchive
    file: ci/tasks/bump-submodule/task.yml
    params:
      SUBMODULE: "libarchive"
    input_mapping:
      source-repo: bsdtar
      module-repo: libarchive
    output_mapping:
      bumped-repo: bumped-libarchive
  - task: bump-zlib
    file: ci/tasks/bump-submodule/task.yml
    params:
      SUBMODULE: "zlib"
    input_mapping:
      source-repo: bumped-libarchive
      module-repo: zlib
    output_mapping:
      bumped-repo: bumped-zlib
  - put: bsdtar
    params:
      repository: bumped-zlib
      rebase: true

- name: build-tar
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: bsdtar
      trigger: true
  - task: build-tar
    file: ci/tasks/build-tar/task.yml
  - put: s3-bucket
    params:
      file: tar-output/tar-*.exe

- name: bosh-agent-update-tar
  serial: true
  plan:
  - aggregate:
    - get: s3-bucket
      trigger: true
      passed: [build-tar]
  - task: create-tracker-task
    params:
      TOKEN: {{TRACKER_GITBOT_TOKEN}}
      PROJECT_ID: {{BOSH_WINDOWS_PROJECT_ID}}
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}
      run:
        path: /bin/bash
        args:
        - -c
        - |
          curl -f -X POST -H "X-TrackerToken: $TOKEN" -H "Content-Type: application/json" -d '{"name":"New Build of Tar available!", "description": "A new build of tar.exe is available at https://greenhouse.ci.cf-app.com/teams/main/pipelines/tar. An update should be made to https://github.com/cloudfoundry/bosh-agent."}' "https://www.pivotaltracker.com/services/v5/projects/$PROJECT_ID/stories"
