resource_types:
- name: command-runner
  type: docker-image
  source:
    repository: cloudfoundrydevelopers/command-runner-resource
    tag: latest

resources:
# Git

- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/garden-windows-ci.git
- name: windowsfs-online-release-develop-2019
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/windowsfs-online-release.git
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    git_config:
    - name: user.email
      value: "pivotal-netgarden-eng@pivotal.io"
    - name: user.name
      value: "Greenhouse CI"
- name: windowsfs-online-github-release
  type: github-release
  source:
    user: cloudfoundry
    repository: windowsfs-online-release
    drafts: true
    access_token: ((GREENHOUSE_CI_ACCESS_TOKEN))


# S3

- name: release-notes
  type: s3
  source:
    bucket: rootfs-release-notes
    regexp: release-notes-(.*)
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
- name: all-kbs-list
  type: s3
  source:
    bucket: rootfs-release-notes
    versioned_file: all-kbs
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
- name: image-version
  type: semver
  source:
    bucket: windows2019fs
    initial_version: 2019.0.1
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))
    key: image-version
    region_name: us-east-1
- name: windowsfs-online-release-version
  type: semver
  source:
    access_key_id: ((BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY))
    bucket: windowsfs
    initial_version: 0.0.0
    key: windowsfs-online-release-version
    region_name: us-east-1

jobs:
- name: generate-release-notes
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: image-version
    - get: all-kbs-list
  - task: generate
    tags: [2019]
    file: ci/tasks/generate-rootfs-release-notes/task.yml
    input_mapping:
      version: image-version
    params:
      EPHEMERAL_DISK_TEMP_PATH: "C:\\var\\vcap\\data\\tmp"
      IMAGE_NAME: cloudfoundry/windows2016fs
      SHARE_IP: ((SHARE_IP))
      SHARE_FQDN: ((SHARE_FQDN))
      SHARE_NAME: ((SHARE_NAME))
      SHARE_USERNAME: ((SHARE_USERNAME))
      SHARE_PASSWORD: ((SHARE_PASSWORD))
  - put: release-notes
    params: {file: notes/release-notes-*}
  - put: all-kbs-list
    params: {file: notes/all-kbs}


- name: shipit-online-patch
  serial: true
  plan:
  - in_parallel:
    - get: ci
    - get: release-notes
      passed: [generate-release-notes]
    - get: windowsfs-online-release-develop-2019
    - get: windowsfs-online-release-version
      params: {bump: patch}
  - task: generate-github-release
    file: ci/tasks/generate-github-release/task.yml
    input_mapping:
      release: windowsfs-online-release-develop-2019
      version: windowsfs-online-release-version
  - put: windowsfs-online-github-release
    params:
      commitish: generated-release/commitish
      name: generated-release/name
      tag: generated-release/version
      body: generated-release/notes
