groups:
- name: main
  jobs:
  - unit-and-integration-tests

resources:
# Git
- name: ci
  type: git
  source:
    branch: web-config-buildpack
    uri: https://github.com/cloudfoundry/garden-windows-ci.git

- name: web-config-buildpack
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry-community/web-config-transform-buildpack.git
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    git_config:
    - name: user.email
      value: "pivotal-netgarden-eng@pivotal.io"
    - name: user.name
      value: "Greenhouse CI"
jobs:
- name: unit-and-integration-tests
  plan:
  - in_parallel:
    - get: ci
    - get: web-config-buildpack
      trigger: true
  - task: run-unit-and-integration-tests
    file: ci/tasks/test-web-config-buildpack/task.yml

