resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/garden-windows-ci.git
- name: groot-windows-develop
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/groot-windows.git
- name: winc-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/winc.git
- name: groot-windows-master
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/groot-windows.git
- name: winc-release-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/winc-release.git
- name: garden-runc-release
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/garden-runc-release.git
- name: gats-fork
  type: git
  source:
    branch: fork-master
    uri: https://github.com/greenhouse-org/garden-integration-tests.git
- name: every-2hrs
  type: time
  source:
    interval: 2h
jobs:
- name: groot-windows
  serial: true
  serial_groups: [windows2016]
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: groot-windows-develop
      trigger: true
      tags: [vsphere]
  - task: test
    input_mapping: { groot-windows: groot-windows-develop }
    file: ci/tasks/test-groot-windows/task.yml
    tags: [((os_version))]

- name: winc
  serial: true
  serial_groups: [window2016]
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: every-2hrs
      trigger: true
      tags: [vsphere]
    - get: winc-develop
      trigger: true
      tags: [vsphere]
    - get: groot-windows-master
      trigger: true
      tags: [vsphere]
  - task: build-groot
    input_mapping: { groot-windows: groot-windows-master }
    file: ci/tasks/build-groot/task.yml
    tags: [((os_version))]
  - task: test
    input_mapping: { winc: winc-develop }
    file: ci/tasks/test-winc/task.yml
    tags: [((os_version))]
    params:
      WINC_TEST_ROOTFS: docker:///cloudfoundry/windows2016fs:((os_version))
      WINC_TEST_PERF_CONCURRENT_CONTAINERS: 20
      WINDOWS_VERSION: ((os_version))

- name: local-gats
  serial: true
  serial_groups: [window2016]
  plan:
  - aggregate:
    - get: ci
      tags: [vsphere]
    - get: every-2hrs
      trigger: true
      tags: [vsphere]
    - get: gats-fork
      tags: [vsphere]
    - get: garden-runc-release
      trigger: true
      tags: [vsphere]
    - get: winc-develop
      passed: [winc]
      trigger: true
      tags: [vsphere]
    - get: winc-release-develop
      tags: [vsphere]
    - get: groot-windows-master
      tags: [vsphere]
  - aggregate:
    - task: build-winc
      file: ci/tasks/build-binary/task.yml
      tags: [((os_version))]
      input_mapping:
        repo: winc-develop
      output_mapping:
        binary-output: winc-binary
      params:
        IMPORT_PATH: "code.cloudfoundry.org/winc"
        PACKAGE: "./cmd/winc"
    - task: build-winc-network
      file: ci/tasks/build-winc-network/task.yml
      tags: [((os_version))]
      input_mapping: { winc: winc-develop }
      params:
        WINDOWS_VERSION: ((os_version))
    - task: build-groot
      input_mapping: { groot-windows: groot-windows-master }
      file: ci/tasks/build-groot/task.yml
      tags: [((os_version))]
    - task: build-nstar
      file: ci/tasks/build-binary/task.yml
      tags: [((os_version))]
      input_mapping:
        repo: winc-release-develop
      output_mapping:
        binary-output: nstar-binary
      params:
        PACKAGE: "./src/nstar"
    - task: build-garden-init
      file: ci/tasks/build-binary/task.yml
      tags: [((os_version))]
      input_mapping:
        repo: garden-runc-release
      output_mapping:
        binary-output: garden-init-binary
      params:
        PACKAGE: "src/code.cloudfoundry.org/guardian/cmd/winit"
        BINARY_NAME: "garden-init.exe"
  - task: copy-forks
    file: ci/tasks/copy-forks/task.yml
    tags: [vsphere]
    input_mapping:
      garden-integration-tests: gats-fork
  - task: run-gats
    file: ci/tasks/run-local-gats/task.yml
    tags: [((os_version))]
    input_mapping:
      garden-runc-release: garden-runc-release-forks
    params:
      WINC_TEST_ROOTFS: docker:///cloudfoundry/windows2016fs:((os_version))
      WINDOWS_VERSION: ((os_version))
