groups:
- name: main
  jobs:
  - bump-go
  - create-release

resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/garden-windows-ci.git

- name: windows-tools-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/windows-tools-release.git
    branch: master
    private_key: {{GREENHOUSE-CI_SSH_KEY}}

- name: windows-tools-release-github
  type: github-release
  source:
    user: cloudfoundry
    repository: windows-tools-release
    drafts: true
    access_token: {{GREENHOUSE_CI_ACCESS_TOKEN}}

- name: golang-release
  type: git
  source:
    uri: https://github.com/bosh-packages/golang-release.git
    tag_filter: v*

jobs:
- name: bump-go
  serial: true
  plan:
  - in_parallel:
    - get: golang-release
      trigger: true
    - get: windows-tools-release
    - get: ci
  - task: bosh-vendor-package
    file: ci/tasks/bosh-vendor-package/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
      PACKAGE: golang-1-windows
    input_mapping:
      release-repo: windows-tools-release
      package-repo: golang-release
  - put: windows-tools-release
    params:
      repository: bumped-release-repo

- name: create-release
  serial: true
  plan:
  - in_parallel:
    - get: windows-tools-release
    - get: ci
  - task: create-release
    file: ci/tasks/create-github-release/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
  - put: windows-tools-release
    params:
      repository: windows-tools-release-bumped
      tag: github-release-info/version
  - put: windows-tools-release-github
    params:
      name: github-release-info/name
      tag: github-release-info/version
