groups:
- name: main
  jobs:
  - bump-go

resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/garden-windows-ci.git

- name: windows-tools-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/windows-tools-release.git
    branch: master
    private_key: {{CF_WINDOWS_TOOLS_DEPLOY_KEY}}

- name: golang-release
  type: git
  source:
    uri: https://github.com/bosh-packages/golang-release.git
    tag_filter: v*

jobs:
- name: bump-go
  serial: true
  plan:
  - in_parallel:
    - get: golang-release
      trigger: true
    - get: windows-tools-release
    - get: ci
  - task: bosh-vendor-package
    file: ci/tasks/bosh-vendor-package/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: {{BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY}}
      PACKAGE: golang-1-windows
    input_mapping:
      release-repo: windows-tools-release
      package-repo: golang-release
  - put: windows-tools-release
    params:
      repository: bumped-release-repo
