resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:

# Git

- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/garden-windows-ci.git

- name: windowsfs-release-develop
  type: git
  source:
    branch: develop
    uri: ((windowsfs-release-develop-uri))
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    git_config:
    - name: user.email
      value: "pivotal-netgarden-eng@pivotal.io"
    - name: user.name
      value: "Greenhouse CI"

- name: windowsfs-release-master
  type: git
  source:
    branch: master
    uri: ((windowsfs-release-master-uri))
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    git_config:
    - name: user.email
      value: "pivotal-netgarden-eng@pivotal.io"
    - name: user.name
      value: "Greenhouse CI"

- name: hydrator
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/hydrator.git
    private_key: ((CLOUDFOUNDRY_HYDRATOR_DEPLOY_KEY))

- name: windows2016fs
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/windows2016fs.git
    private_key: ((CLOUDFOUNDRYINCUBATOR_WINDOWS2016FS_DEPLOY_KEY))
    ignore_paths: [ ((os-version))/Dockerfile ]

- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests

- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: cf-deployment
  type: git
  source:
    branch: release-candidate
    uri: https://github.com/cloudfoundry/cf-deployment.git

- name: winc-release-master
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/winc-release.git

- name: garden-windows-environments
  type: git
  source:
    branch: master
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    uri: git@github.com:pivotal/garden-windows-environments

# GitHub Release

- name: windowsfs-release-github-release
  type: github-release
  source:
    user: cloudfoundry
    repository: ((windowsfs-release-repo))
    drafts: true
    access_token: ((GREENHOUSE_CI_ACCESS_TOKEN))

# S3

- name: gcp-windows-stemcell
  type: s3
  source:
    bucket: all-bosh-windows
    regexp: ((stemcell-regexp))
    access_key_id: ((BOSH_WINDOWS_BOSH_CI_S3_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_BOSH_CI_S3_SECRET_ACCESS_KEY))

# Semver

- name: windowsfs-release-version
  type: semver
  source:
    access_key_id: ((BOSH_WINDOWS_S3_ADMIN_ACCESS_KEY_ID))
    secret_access_key: ((BOSH_WINDOWS_S3_ADMIN_SECRET_ACCESS_KEY))
    bucket: ((fs-version))
    initial_version: ((initial-release-version))
    key: windowsfs-release-version
    region_name: us-east-1

# BOSH Deployment

- name: sriracha-cf-deployment
  type: bosh-deployment
  source:
    deployment: cf
    client: ((SRIRACHA_BOSH_CLIENT))
    client_secret: ((SRIRACHA_BOSH_CLIENT_SECRET))
    ca_cert: ((SRIRACHA_BOSH_CA_CERT))
    target: ((SRIRACHA_BOSH_ENVIRONMENT))
    jumpbox_url: ((SRIRACHA_JUMPBOX_URL))
    jumpbox_ssh_key: ((SRIRACHA_JUMPBOX_SSH_KEY))

- name: sriracha-smoke-test-deployment
  type: bosh-deployment
  source:
    deployment: ((fs-version))
    client: ((SRIRACHA_BOSH_CLIENT))
    client_secret: ((SRIRACHA_BOSH_CLIENT_SECRET))
    ca_cert: ((SRIRACHA_BOSH_CA_CERT))
    target: ((SRIRACHA_BOSH_ENVIRONMENT))
    jumpbox_url: ((SRIRACHA_JUMPBOX_URL))
    jumpbox_ssh_key: ((SRIRACHA_JUMPBOX_SSH_KEY))

# Lock Pool

- name: sriracha-lock-pool
  type: pool
  source:
    branch: master
    pool: sriracha
    private_key: ((GREENHOUSE-CI_SSH_KEY))
    uri: git@github.com:greenhouse-ci/locks

groups:
- name: ((fs-version))
  jobs:
    - bump-windowsfs-release-windows2016fs
    - bump-windowsfs-release-hydrator
- name: windowsfs-release
  jobs:
    - test-create-release-windows
    - test-create-release-linux
    - sriracha-offline-cats
    - sriracha-offline-smoke-test
    - shipit-offline-major
    - shipit-offline-minor
    - shipit-offline-patch

jobs:
- name: bump-windowsfs-release-windows2016fs
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: windowsfs-release-develop
    - get: windows2016fs
      trigger: true
  - task: bump-windowsfs-release
    file: ci/tasks/bump-submodule/task.yml
    params:
      SUBMODULE: "src/code.cloudfoundry.org/windows2016fs"
    input_mapping:
      source-repo: windowsfs-release-develop
      module-repo: windows2016fs
  - task: update-blob
    file: ci/tasks/update-windows2016fs-blob/task.yml
    params:
      FS_VERSION: ((fs-version))
      OS_VERSION: "((os-version))"
    input_mapping:
      windowsfs-release: bumped-repo
  - task: commit-changes
    file: ci/tasks/commit/task.yml
    input_mapping:
      repo: windowsfs-release-updated-blob
    output_mapping:
      repo_with_commit: windowsfs-release-updated-commit
    params:
      MESSAGE: "Updated image blob"
  - put: windowsfs-release-develop
    params:
      repository: windowsfs-release-updated-commit
      rebase: false

- name: bump-windowsfs-release-hydrator
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: windowsfs-release-develop
    - get: hydrator
      trigger: true
  - task: bump-windowsfs-release
    file: ci/tasks/bump-submodule/task.yml
    params:
      SUBMODULE: "src/code.cloudfoundry.org/hydrator"
    input_mapping:
      source-repo: windowsfs-release-develop
      module-repo: hydrator
  - put: windowsfs-release-develop
    params:
      repository: bumped-repo
      rebase: false

- name: test-create-release-windows
  serial: true
  plan:
  - aggregate:
    - get: ci
      tags: ((resource-get-tag))
    - get: windowsfs-release-develop
      tags: ((resource-get-tag))
      trigger: true
  - aggregate:
    - task: create-dev-release
      tags: ((task-tag))
      file: ci/tasks/create-fs-release-windows/task.yml
      input_mapping:
        windowsfs-release: windowsfs-release-develop
      params:
        EPHEMERAL_DISK_TEMP_PATH: "C:\\var\\vcap\\data\\tmp"
    - task: run-ginkgo-exe
      tags: ((task-tag))
      file: ci/tasks/ginkgo-from-gopath-windows/task.yml
      input_mapping: { repo: windowsfs-release-develop}
      params:
        TEST_PATH: src/create
        EPHEMERAL_DISK_TEMP_PATH: "C:\\var\\vcap\\data\\tmp"

- name: test-create-release-linux
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: windowsfs-release-develop
      trigger: true
  - aggregate:
    - task: create-dev-release
      file: ci/tasks/create-fs-release-linux/task.yml
      input_mapping:
        windowsfs-release: windowsfs-release-develop
    - task: run-ginkgo
      file: ci/tasks/ginkgo-from-gopath-linux/task.yml
      input_mapping: { repo: windowsfs-release-develop}
      params:
        TEST_PATH: src/create

- name: sriracha-offline-cats
  serial: true
  plan:
  - put: sriracha-lock-pool
    params:
      acquire: true
  - aggregate:
    - get: ci
    - get: windowsfs-release-develop
      passed: [test-create-release-windows, test-create-release-linux]
      trigger: true
    - get: cf-acceptance-tests
    - get: cf-deployment-concourse-tasks
    - get: cf-deployment
    - get: gcp-windows-stemcell
    - get: garden-windows-environments
  - aggregate:
    - task: get-linux-stemcell
      file: ci/tasks/get-gcp-linux-stemcell/task.yml
      output_mapping: { stemcell: gcp-linux-stemcell }
    - task: create-windowsfs-release
      file: ci/tasks/create-fs-release-linux/task.yml
      input_mapping:
        windowsfs-release: windowsfs-release-develop
      output_mapping:
        release-tarball: windowsfs-tarball
  - task: create-windowsfs-opsfile
    file: ci/tasks/write-windows2016fs-opsfile/task.yml
    params:
      FS_VERSION: ((fs-version))
    input_mapping: { release-tarball: windowsfs-tarball }
  - task: delete-deployments
    file: ci/tasks/bosh-delete-deployments/task.yml
    params:
      BOSH_CA_CERT: ((SRIRACHA_BOSH_CA_CERT))
      BOSH_CLIENT: ((SRIRACHA_BOSH_CLIENT))
      BOSH_CLIENT_SECRET: ((SRIRACHA_BOSH_CLIENT_SECRET))
      BOSH_ENVIRONMENT: ((SRIRACHA_BOSH_ENVIRONMENT))
      JUMPBOX_IP: ((SRIRACHA_JUMPBOX_IP))
      JUMPBOX_SSH_KEY: ((SRIRACHA_JUMPBOX_SSH_KEY))
  - task: delete-stemcells
    file: ci/tasks/bosh-delete-stemcells/task.yml
    params:
      BOSH_CA_CERT: ((SRIRACHA_BOSH_CA_CERT))
      BOSH_CLIENT: ((SRIRACHA_BOSH_CLIENT))
      BOSH_CLIENT_SECRET: ((SRIRACHA_BOSH_CLIENT_SECRET))
      BOSH_DEPLOYMENT: cf
      BOSH_ENVIRONMENT: ((SRIRACHA_BOSH_ENVIRONMENT))
      JUMPBOX_IP: ((SRIRACHA_JUMPBOX_IP))
      JUMPBOX_SSH_KEY: ((SRIRACHA_JUMPBOX_SSH_KEY))
  - put: sriracha-cf-deployment
    params:
      manifest: cf-deployment/cf-deployment.yml
      stemcells:
      - gcp-linux-stemcell/*.tgz
      - gcp-windows-stemcell/*.tgz
      releases:
      - windowsfs-tarball/*.tgz
      ops_files:
      - cf-deployment/operations/scale-to-one-az.yml
      - ci/operations/use-2-azs-for-router.yml
      - ((windows-cell-ops-file))
      - ((latest-windows-stemcell-ops-file))
      - ((windows-scale-down-ops-file))
      - ((windows-rdp-ops-file))
      - windowsfs-opsfile/specified-windowsfs-version.yml
      - ((use-offline-fs-opsfile))
      vars_files:
      - garden-windows-environments/sriracha/cf/vars.yml
      cleanup: true
    get_params:
      skip_export: true
  - task: generate-integration-config
    file: ci/tasks/generate-integration-config/task.yml
    params:
      ADMIN_PASSWORD: ((SRIRACHA_ADMIN_PASSWORD))
      ADMIN_USER: admin
      API: api.sriracha.cf-app.com
      APPS_DOMAIN: sriracha.cf-app.com
      UNALLOCATED_IP: 10.0.0.5
      WINDOWS_STACK: windows2016
  - task: cats
    file: cf-deployment-concourse-tasks/run-cats/task.yml
    params:
      NODES: 4
    on_success:
      task: delete-deployment
      file: ci/tasks/bosh-deld/task.yml
      params:
        BOSH_CA_CERT: ((SRIRACHA_BOSH_CA_CERT))
        BOSH_CLIENT: ((SRIRACHA_BOSH_CLIENT))
        BOSH_CLIENT_SECRET: ((SRIRACHA_BOSH_CLIENT_SECRET))
        BOSH_DEPLOYMENT: cf
        BOSH_ENVIRONMENT: ((SRIRACHA_BOSH_ENVIRONMENT))
        JUMPBOX_IP: ((SRIRACHA_JUMPBOX_IP))
        JUMPBOX_SSH_KEY: ((SRIRACHA_JUMPBOX_SSH_KEY))
  ensure:
    put: sriracha-lock-pool
    params:
      release: sriracha-lock-pool

- name: sriracha-offline-smoke-test
  serial: true
  plan:
  - put: sriracha-lock-pool
    params:
      acquire: true
  - aggregate:
    - get: ci
    - get: windowsfs-release-develop
      passed: [test-create-release-windows, test-create-release-linux]
      trigger: true
    - get: winc-release-master
      trigger: true
    - get: gcp-windows-stemcell
  - aggregate:
    - task: create-windowsfs-release
      file: ci/tasks/create-fs-release-linux/task.yml
      input_mapping:
        windowsfs-release: windowsfs-release-develop
      output_mapping:
        release-tarball: windowsfs-tarball
    - task: create-winc-release
      file: ci/tasks/bosh-cr/task.yml
      input_mapping:
        release: winc-release-master
      output_mapping:
        release-tarball: winc-tarball
  - task: create-windowsfs-opsfile
    file: ci/tasks/write-windows2016fs-opsfile/task.yml
    params:
      FS_VERSION: ((fs-version))
    input_mapping: { release-tarball: windowsfs-tarball }
  - task: delete-deployments
    file: ci/tasks/bosh-delete-deployments/task.yml
    params:
      BOSH_CA_CERT: ((SRIRACHA_BOSH_CA_CERT))
      BOSH_CLIENT: ((SRIRACHA_BOSH_CLIENT))
      BOSH_CLIENT_SECRET: ((SRIRACHA_BOSH_CLIENT_SECRET))
      BOSH_ENVIRONMENT: ((SRIRACHA_BOSH_ENVIRONMENT))
      JUMPBOX_IP: ((SRIRACHA_JUMPBOX_IP))
      JUMPBOX_SSH_KEY: ((SRIRACHA_JUMPBOX_SSH_KEY))
  - task: delete-stemcells
    file: ci/tasks/bosh-delete-stemcells/task.yml
    params:
      BOSH_CA_CERT: ((SRIRACHA_BOSH_CA_CERT))
      BOSH_CLIENT: ((SRIRACHA_BOSH_CLIENT))
      BOSH_CLIENT_SECRET: ((SRIRACHA_BOSH_CLIENT_SECRET))
      BOSH_DEPLOYMENT: ((fs-version))
      BOSH_ENVIRONMENT: ((SRIRACHA_BOSH_ENVIRONMENT))
      JUMPBOX_IP: ((SRIRACHA_JUMPBOX_IP))
      JUMPBOX_SSH_KEY: ((SRIRACHA_JUMPBOX_SSH_KEY))
  - put: sriracha-smoke-test-deployment
    params:
      manifest: windowsfs-release-develop/manifests/smoke-test.yml
      stemcells:
      - gcp-windows-stemcell/*.tgz
      releases:
      - windowsfs-tarball/*.tgz
      - winc-tarball/*.tgz
      ops_files:
      - windowsfs-opsfile/specified-windowsfs-version.yml
      cleanup: true
    get_params:
      skip_export: true
  - task: smoke-test
    file: ci/tasks/fs-smoke-test/task.yml
    params:
      FS_VERSION: ((fs-version))
      BOSH_CA_CERT: ((SRIRACHA_BOSH_CA_CERT))
      BOSH_CLIENT: ((SRIRACHA_BOSH_CLIENT))
      BOSH_CLIENT_SECRET: ((SRIRACHA_BOSH_CLIENT_SECRET))
      BOSH_ENVIRONMENT: ((SRIRACHA_BOSH_ENVIRONMENT))
      JUMPBOX_IP: ((SRIRACHA_JUMPBOX_IP))
      JUMPBOX_SSH_KEY: ((SRIRACHA_JUMPBOX_SSH_KEY))
    on_success:
      task: delete-deployment
      file: ci/tasks/bosh-deld/task.yml
      params:
        BOSH_CA_CERT: ((SRIRACHA_BOSH_CA_CERT))
        BOSH_CLIENT: ((SRIRACHA_BOSH_CLIENT))
        BOSH_CLIENT_SECRET: ((SRIRACHA_BOSH_CLIENT_SECRET))
        BOSH_DEPLOYMENT: ((fs-version))
        BOSH_ENVIRONMENT: ((SRIRACHA_BOSH_ENVIRONMENT))
        JUMPBOX_IP: ((SRIRACHA_JUMPBOX_IP))
        JUMPBOX_SSH_KEY: ((SRIRACHA_JUMPBOX_SSH_KEY))
  ensure:
    put: sriracha-lock-pool
    params:
      release: sriracha-lock-pool

- name: shipit-offline-major
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: windowsfs-release-master
    - get: windowsfs-release-develop
      passed: [sriracha-offline-cats, sriracha-offline-smoke-test]
    - get: windowsfs-release-version
      params: {bump: major}
  - task: update-version-and-shas
    file: ci/tasks/update-fs-release-version/task.yml
    params:
      FS_VERSION: ((fs-version))
    input_mapping:
      windowsfs-release: windowsfs-release-develop
      version: windowsfs-release-version
  - put: windowsfs-release-master
    params:
      repository: windowsfs-release-updated-version
      tag: windowsfs-release-version/version
      tag_prefix: v
  - put: windowsfs-release-develop
    params:
      repository: windowsfs-release-updated-version
      merge: true
  - task: generate-github-release
    input_mapping:
      release: windowsfs-release-updated-version
      version: windowsfs-release-version
    file: ci/tasks/generate-github-release/task.yml
  - put: windowsfs-release-github-release
    params:
      commitish: generated-release/commitish
      name: generated-release/name
      tag: generated-release/version
  - put: windowsfs-release-version
    params:
      file: windowsfs-release-version/version

- name: shipit-offline-minor
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: windowsfs-release-master
    - get: windowsfs-release-develop
      passed: [sriracha-offline-cats, sriracha-offline-smoke-test]
    - get: windowsfs-release-version
      params: {bump: minor}
  - task: update-version-and-shas
    file: ci/tasks/update-fs-release-version/task.yml
    input_mapping:
      windowsfs-release: windowsfs-release-develop
      version: windowsfs-release-version
  - put: windowsfs-release-master
    params:
      repository: windowsfs-release-updated-version
      tag: windowsfs-release-version/version
      tag_prefix: v
  - put: windowsfs-release-develop
    params:
      repository: windowsfs-release-updated-version
      merge: true
  - task: generate-github-release
    input_mapping:
      release: windowsfs-release-updated-version
      version: windowsfs-release-version
    file: ci/tasks/generate-github-release/task.yml
  - put: windowsfs-release-github-release
    params:
      commitish: generated-release/commitish
      name: generated-release/name
      tag: generated-release/version
  - put: windowsfs-release-version
    params:
      file: windowsfs-release-version/version

- name: shipit-offline-patch
  serial: true
  plan:
  - aggregate:
    - get: ci
    - get: windowsfs-release-master
    - get: windowsfs-release-develop
      passed: [sriracha-offline-cats, sriracha-offline-smoke-test]
    - get: windowsfs-release-version
      params: {bump: patch}
  - task: update-version-and-shas
    file: ci/tasks/update-fs-release-version/task.yml
    input_mapping:
      windowsfs-release: windowsfs-release-develop
      version: windowsfs-release-version
  - put: windowsfs-release-master
    params:
      repository: windowsfs-release-updated-version
      tag: windowsfs-release-version/version
      tag_prefix: v
  - put: windowsfs-release-develop
    params:
      repository: windowsfs-release-updated-version
      merge: true
  - task: generate-github-release
    input_mapping:
      release: windowsfs-release-updated-version
      version: windowsfs-release-version
    file: ci/tasks/generate-github-release/task.yml
  - put: windowsfs-release-github-release
    params:
      commitish: generated-release/commitish
      name: generated-release/name
      tag: generated-release/version
  - put: windowsfs-release-version
    params:
      file: windowsfs-release-version/version
