---
platform: windows

inputs:
- name: ci
- name: winc
  path: src/code.cloudfoundry.org/winc

outputs:
- name: winc-network-binary

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/build-winc-network/run.ps1
  path: powershell
  args:
  - "/C"
  - "mkdir $env:TMP -ea 0"

params:
  WINDOWS_VERSION:
  TMP:
  TEMP:
