---
platform: windows

inputs:
- name: ci
- name: winc

outputs:
- name: winc-network-binary

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/build-winc-network/run.ps1

params:
  WINDOWS_VERSION:
  EPHEMERAL_DISK_TEMP_PATH:
