#!/usr/bin/env bash

# 1. Check lock
# 2. If already locked exit
# 3. else acquire lock
# 4. bbl destroy
# 5. run bbl up script
# 6. release lock
set -eux

setup_github_ssh() {
  mkdir -p ~/.ssh

  private_key=${private_key// //\n}
  private_key=${private_key//\/nRSA\/nPRIVATE\/n/ RSA PRIVATE }

  echo "$private_key" > ~/.ssh/rep_private_key
  chmod 600 ~/.ssh/rep_private_key

  eval $(ssh-agent) >/dev/null 2>&1 DISPLAY=
  ssh-add ~/.ssh/rep_private_key >/dev/null

  cat > ~/.ssh/config <<EOF
  StrictHostKeyChecking no
  LogLevel quiet
EOF
  chmod 0600 ~/.ssh/config
  ssh-keyscan github.com >> ~/.ssh/known_hosts

}

release_lock() {
  if [ -f ci-lock/$env/unclaimed/$env ]; then
    echo "$env is already unclaimed. Exiting"
    return 0
  fi

  pushd ci-lock
    git checkout master
    git mv $env/claimed/$env $env/unclaimed/$env
    git -c user.name="Garden Windows CI" -c user.email="<>" commit --author "environments-pipeline <>" -m "environments/bbl-update-$env unclaiming: $env"
    git push origin master
  popd
  echo Released $env
}

get_lock_or_die() {

  if [ -f ci-lock/$env/claimed/$env ]; then
    echo "$env is claimed. Exiting"
    exit 0
  fi
  pushd ci-lock
    git checkout master
    git mv $env/unclaimed/$env $env/claimed/$env
    git -c user.name="Garden Windows CI" -c user.email="<>" commit --author "environments-pipeline <>" -m "environments/bbl-update-$env claiming: $env"
    git push origin master
  popd
  echo Claimed $env
}

setup_github_ssh
get_lock_or_die
release_lock
bbl=binary-dir/bbl_executable


