#!/usr/bin/env bash

# 1. Check lock
# 2. If already locked exit
# 3. else acquire lock
# 4. bbl destroy
# 5. run bbl up script
# 6. release lock
set -eux

release_lock() {
  if [ -f ci-lock/$env/unclaimed/$env ]; then
    echo "$env is already unclaimed. Exiting"
    return 0
  fi

  pushd ci-lock
    git mv $env/claimed/$env $env/unclaimed/$env
    GIT_SSH_COMMAND='ssh -i <($GREENHOUSE-CI_SSH_KEY)' git -c user.name="Garden Windows CI" -c user.email="<>" commit --author "environments-pipeline <>" -m "environments/bbl-update-$env unclaiming: $env"
    git push origin master
  popd
  echo Released $env
}

get_lock_or_die() {

  if [ -f ci-lock/$env/claimed/$env ]; then
    echo "$env is claimed. Exiting"
    exit 0
  fi
  pushd ci-lock
    git mv $env/unclaimed/$env $env/claimed/$env
    GIT_SSH_COMMAND='ssh -i <($GREENHOUSE-CI_SSH_KEY)' git -c user.name="Garden Windows CI" -c user.email="<>" commit --author "environments-pipeline <>" -m "environments/bbl-update-$env claiming: $env"
    git push origin master
  popd
  echo Claimed $env
}


get_lock_or_die
release_lock
bbl=binary-dir/bbl_executable


