---
platform: linux
image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}

inputs:
- name: ci
- name: binary-dir
- name: ci-lock

params:
  env:
  iaas:
  iaas-service-account-key:
  iaas-region:
  GREENHOUSE-CI_SSH_KEY:

run:
  path: ci/tasks/refresh-director/run
