---
platform: windows

inputs:
- name: ci
- name: windows2016fs-release

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/create-fs-release-windows/run.ps1
