---
platform: windows

inputs:
- name: ci
- name: windowsfs-release

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/create-fs-release-windows/run.ps1

params:
  TMP: "C:\\var\\vcap\\data\\tmp"
  GOTMPDIR: "C:\\var\\vcap\\data\\tmp"
  TEMP: "C:\\var\\vcap\\data\\tmp"
