---
platform: windows

inputs:
- name: ci
- name: envoy

outputs:
- name: envoy-exe

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/envoy-ci-windows/run.ps1

params:
  BUILD_TYPE:
