#!/bin/bash

main() {
  ROOT_DIR="${1}"

  pushd "${ROOT_DIR}/bbl-state/${BBL_STATE_DIR}" > /dev/null

    eval "$(bbl print-env)"

cat << EOF > integration-config/integration_config.kson
{
  "api": "$API",
  "apps_domain": "$APPS_DOMAIN",
  "admin_user": "$ADMIN_USER",
  "admin_password": "$ADMIN_PASSWORD",
  "skip_ssl_validation": true,
  "include_apps": false,
  "include_detect": false,
  "include_persistent_app": false,
  "include_routing": false,
  "include_v3": false,
  "include_capi_no_bridge": false,
  "include_security_groups": true,
  "use_http": true,
  "include_windows": true,
  "include_ssh": true,
  "credhub_mode": "$CREDHUB_MODE",
  "credhub_client": "$CREDHUB_CLIENT",
  "credhub_secret": "$CREDHUB_SECRET",
  "unallocated_ip_for_security_group": "$UNALLOCATED_IP",
  "use_windows_test_task": true,
  "use_windows_context_path": true,
  "windows_stack": "$WINDOWS_STACK"
}
EOF

  popd > /dev/null
}

main ${PWD}

