#!/usr/bin/env bash

set -eu

. ci/bin/ci_helpers

trap _close_ssh_connection EXIT
cmd=$(_bosh_socks5_env "$JUMPBOX_IP" "$JUMPBOX_SSH_KEY")
eval "$cmd"

bosh -d "$FS_VERSION" run-errand "$FS_VERSION-smoke-test"
