---
platform: linux

image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}

inputs:
- name: ci

params:
  FS_VERSION:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  JUMPBOX_IP:
  JUMPBOX_SSH_KEY:

run:
  path: ci/tasks/fs-smoke-test/run
