---
platform: windows

inputs:
- name: ci
- name: repo

outputs:
- name: binary-output

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/build-binary/run.ps1

params:
  IMPORT_PATH:
  PACKAGE:
  BINARY_NAME:
  EPHEMERAL_DISK_TEMP_PATH:
