---
platform: linux
image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}

inputs:
- name: ci
- name: bosh-deployment

run:
  path: ci/tasks/bosh-update-runtime-config-dns/run

params:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  JUMPBOX_IP:
  JUMPBOX_SSH_KEY:
