---
platform: windows

inputs:
- name: ci
- name: image-version

outputs:
- name: notes

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/generate-rootfs-metadata/run.ps1

params:
  IMAGE_NAME: ""
  EPHEMERAL_DISK_TEMP_PATH:
