#!/bin/bash

set -e

export PATH=$(pwd)/bin:$PATH
export GOPATH=$(pwd)

pushd src/github.com/teddyking/cfbench
go install
popd

cf api "$CF_API" --skip-ssl-validation
CF_DIAL_TIMEOUT=20 cf login -u "$CF_USERNAME" -p "$CF_PASSWORD" -s "$CF_SPACE" -o "$CF_ORG" --skip-ssl-validation

function finish {
	# delete any orphaned apps and routes
	cf apps | grep benchme | cut -d " " -f1 | xargs -I {} cf d -f -r {}
}
trap finish EXIT

export CF_AUTH_TOKEN=$(cf oauth-token)
DOPPLER_ADDRESS=$(cf curl /v2/info | jq '.doppler_logging_endpoint' -r)

set +e

if [ ! -z "$APP_START_COMMAND" ]; then
  APP_START_COMMAND="-startCommand $APP_START_COMMAND"
fi

if [ ! -z "$APP_BUILDPACK" ]; then
  APP_BUILDPACK="-buildpack $APP_BUILDPACK"
fi

cfbench \
  -stack $CF_STACK \
  -app-dir $APP_DIR \
  $APP_BUILDPACK \
  $APP_START_COMMAND \
  -doppler-address "$DOPPLER_ADDRESS" \
  -tag $CF_STACK \
  -json > metrics.json

pushExitStatus=$?

set -e

if [[ $pushExitStatus == "0" ]]; then
  curl -X POST -H 'Content-Type: application/json' -d @metrics.json \
   "https://app.datadoghq.com/api/v1/series?api_key=$DATADOG_API_KEY&application_key=$DATADOG_APPLICATION_KEY"
else
  curl -X POST -H "Content-type: application/json" \
    -d "{ \"series\" :
           [{\"metric\": \"cfbench.failed\",
            \"points\": [[$(date +%s), $pushExitStatus]],
            \"type\": \"gauge\",
            \"tags\": [\"$CF_STACK\"]
          }]
        }" \
  "https://app.datadoghq.com/api/v1/series?api_key=${DATADOG_API_KEY}&application_key=$DATADOG_APPLICATION_KEY"
fi

exit $pushExitStatus
