---
platform: windows

inputs:
- name: ci
- name: version
- name: repo
- name: git-setup
- name: tar
- name: vcredist-2010
- name: vcredist-ucrt
- name: dotnet-48-installer
  optional: true

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/tasks/docker-build-and-push/run.ps1

params:
  DOCKERFILE: ""
  IMAGE_NAME: ""
  DOCKER_USERNAME: ""
  DOCKER_PASSWORD: ""
  OS_VERSION: ""
  EPHEMERAL_DISK_TEMP_PATH:
