#!/usr/bin/env bash

set -eu

ops="
---
- type: replace
  path: /stemcells/alias=xenial/version
  value: "$(< stemcell/version)"

- type: replace
  path: /releases/name=concourse
  value:
    name: concourse
    sha1: "$(< concourse-release/sha1)"
    url: "$(< concourse-release/url)"
    version: "$(< concourse-release/version)"
"

eval "$(bbl --state-dir=garden-windows-environments/mulgore print-env)"
bosh -d ${BOSH_DEPLOYMENT} manifest > artifacts/manifest.yml.OLD
bosh int artifacts/manifest.yml.OLD -o <(echo "${ops}") > artifacts/manifest.yml

echo "deployment: ${BOSH_DEPLOYMENT}" > artifacts/source-file.yml
echo "${BOSH_CREDENTIALS}" >> artifacts/source-file.yml
