#!/usr/bin/env bash

set -eu

. ci/bin/ci_helpers

trap _close_ssh_connection EXIT
cmd=$(_bosh_socks5_env "$JUMPBOX_IP" "$JUMPBOX_SSH_KEY")
eval "$cmd"

echo "Trying to upload release"
bosh runtime-config --name=dns > /tmp/rc.yml
if [[ $? != 0 ]]; then
  echo "No runtime config to update"
  exit 0
fi
RELEASE_URL=$(bosh int --path=/releases/name=bosh-dns/url /tmp/rc.yml)
RELEASE_SHA=$(bosh int --path=/releases/name=bosh-dns/sha1 /tmp/rc.yml)
bosh upload-release --sha1 "$RELEASE_SHA" "$RELEASE_URL"
