#!/bin/sh

set -e

( cd release && git rev-parse HEAD ) > generated-release/commitish

version=$(cat version/number)
echo "v$version" > generated-release/name
echo "v$version" > generated-release/version

if [ -d release-notes ]; then
  cp release-notes/release-notes-* generate-release/notes
fi
