#!/bin/bash

set -eu

cf api "$CF_API" --skip-ssl-validation
cf login -u "$CF_USERNAME" -p "$CF_PASSWORD" -o system

cf create-isolation-segment windows2019

cf create-org cfbench
cf enable-org-isolation cfbench windows2019
cf target -o cfbench
cf create-space windows2012R2
cf create-space windows2019
cf set-space-isolation-segment windows2019 windows2019

cf create-org longrunning
cf enable-org-isolation longrunning windows2019
cf target -o longrunning
cf create-space windows2012R2
cf create-space windows2019
cf set-space-isolation-segment windows2019 windows2019


