#!/usr/bin/env bash

set -eu

. ci/bin/ci_helpers

trap _close_ssh_connection EXIT
cmd=$(_bosh_socks5_env "$JUMPBOX_IP" "$JUMPBOX_SSH_KEY")
eval "$cmd"

deployments=$(bosh deployments --json | jq -r '.Tables[].Rows[].name')

for deployment in $deployments;
do
  if [[ ! -z "$deployment" ]]; then
    echo "Deleting deployment: $deployment"
    bosh -n -d "$deployment" delete-deployment --force
  fi
done
