- name: Install core packages (linux)
  when: is_ubuntu
  package: name={{ item }}
  with_items:
    - build-essential
    - openssh-server
    - smbclient
    - xsel
    - htop
    - tree
    - jq
    - python3-pip
    - silversearcher-ag
    - cmake
    - direnv
    - ruby
    - mingw-w64
    - auditd
    - gnome-tweaks
    - ubuntu-desktop
    - ninja-build
    - git-core
    - debhelper
    - cdbs
    - dpkg-dev
    - autotools-dev
    - pkg-config
    - xmlto
    - libssl-dev
    - docbook-xsl
    - xsltproc
    - libxkbfile-dev
    - libx11-dev
    - libwayland-dev
    - libxrandr-dev
    - libxi-dev
    - libxrender-dev
    - libxext-dev
    - libxinerama-dev
    - libxfixes-dev
    - libxcursor-dev
    - libxv-dev
    - libxdamage-dev
    - libxtst-dev
    - libcups2-dev
    - libpcsclite-dev
    - libasound2-dev
    - libpulse-dev
    - libjpeg-dev
    - libgsm1-dev
    - libusb-1.0-0-dev
    - libudev-dev
    - libdbus-glib-1-dev
    - uuid-dev
    - libxml2-dev
    - libgstreamer1.0-dev
    - libgstreamer-plugins-base1.0-dev
    - libavutil-dev
    - libavcodec-dev
    - libavresample-dev
- name: Turn on firewall
  when: is_ubuntu
  shell: ufw enable
  become: yes
- name: firewall enable ssh
  when: is_ubuntu
  shell: ufw allow ssh
  become: yes

- name: Install ubuntu-restricted-extras (linux)
  when: is_ubuntu
  package: name=ubuntu-restricted-extras

- name: Install core packages (osx)
  when: is_osx
  package: name={{ item }}
  with_items:
    - coreutils
    - findutils
    - gawk
    - gnu-getopt
    - gnu-indent
    - gnu-sed
    - gnu-tar
    - gnutls
    - wget
    - gpg
    - grc
    - pstree
    - unrar
    - watch
    - the_silver_searcher
    - direnv
    - jq
    - openssl
    - python3
    - the_silver_searcher
    - mingw-w64
    - go
    - git-duet
    - dep
  become: yes
  become_user: pivotal
- name: Install apps (osx)
  homebrew_cask: name={{ item }}
  when: is_osx
  with_items:
    - flycut
    - flux
    - shiftit
    - docker
    - tunnelblick
  become: yes
  become_user: pivotal
