- name: Add DELL apt keys
  when: is_ubuntu
  apt_key:
    id=F9FDA6BED73CDC22
    keyserver=keyserver.ubuntu.com
    state=present
- name: Add Dell PPA
  when: is_ubuntu
  apt_repository: repo={{ item }}
  with_items:
    - 'deb http://dell.archive.canonical.com/updates/ bionic-dell public'
    - 'deb-src http://dell.archive.canonical.com/updates/ bionic-dell public'
    - 'deb http://dell.archive.canonical.com/updates/ bionic-oem public'
    - 'deb-src http://dell.archive.canonical.com/updates/ bionic-oem public'
