#!/usr/bin/env bash

set -eux

NEW_VERSION=$(cat version/version)

pushd windows2016fs-release
	echo -n $NEW_VERSION > VERSION

	git config --global user.email "pivotal-netgarden-eng@pivotal.io"
	git config --global user.name "Greenhouse CI"
	git add VERSION

	commit_message="Bumped version to $NEW_VERSION"
	git commit -m "$(echo -e $commit_message)"
popd

cp -r windows2016fs-release/. windows2016fs-release-updated-version

