---
platform: linux

image_resource: {type: docker-image, source: {repository: cloudfoundry/garden-windows-ci}}

inputs:
  - name: ci
  - name: version
  - name: windowsfs-release

outputs:
  - name: windowsfs-release-updated-version

run:
  path: ci/tasks/update-fs-release-version/run

